import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root = join(__dirname, "..", "..");
const read = (path: string) => readFileSync(join(root, path), "utf8");
const page = read("src/components/content/AccountsWorkloadsPage.tsx");
const content = read("src/components/content/index.tsx");
const app = read("src/components/app.tsx");
const styles = read("src/styles/app.css");

assert.match(page, /deleteMode === "permanent" \|\| deleteMode === "mixed"/, "deleted and mixed selections require confirmation");
assert.match(page, /filter\(\(id\) => rows\.find\(\(row\) => row\.id === id\)\?\.isDeleted\)/, "permanent targets are isolated from selected deleted rows");
assert.match(page, /applyDraftDelete\([\s\S]*activeIds/, "mixed confirmation stages active rows for draft deletion");
assert.match(page, />Delete<\/oj-button>/, "destructive action label is always Delete");
assert.doesNotMatch(page, /\{deleteMode ===|Selected rows:/, "dynamic top-action delete labels and selected count are absent");
assert.match(page, /hasSelectedDeletedRows[\s\S]*&& \([\s\S]*>Restore<\/oj-button>/, "Restore is conditionally rendered for deleted selections");
assert.match(page, />Refresh<\/oj-button>/, "Refresh action is rendered");
assert.match(page, /accounts-workloads-notes-content[^>]*title=/, "Notes exposes full content through a native tooltip");
assert.match(content, /oj-progress-circle[\s\S]*value=\{-1\}/, "initial load uses an indeterminate JET progress circle");
assert.match(app, /getNavigationRouteFromPath\(window\.location\.pathname\)/, "initial route comes from the browser pathname");
assert.match(app, /window\.history\.pushState[\s\S]*getNavigationPath\(route\)/, "navigation updates the canonical URL");
assert.match(app, /addEventListener\("popstate"/, "Back and Forward update the active route");
assert.doesNotMatch(app, /onFiscalYearChange=\{\(year\) => \{[\s\S]*setSelectedNavigationId\("home"\)/, "FY changes retain navigation selection and route");
assert.match(styles, /@media \(min-width: 1025px\)[\s\S]*?\.kpi-side-nav[\s\S]*?width: 16\.5rem/, "desktop navigation is 16.5rem wide");
assert.match(styles, /\.kpi-navigation-label[^}]*font-size: 0\.84rem/, "desktop navigation labels use the compact font size");
assert.match(app, /class="kpi-navigation-label"[^>]*title=\{item\.label\}[^>]*tabIndex=\{0\}/, "every navigation label exposes its full name natively and accepts keyboard focus");
assert.match(app, /class="kpi-navigation-full-name"[^>]*role="tooltip"[^>]*>\{item\.label\}/, "every navigation label renders a keyboard-focus full-name tooltip");
assert.match(styles, /\.kpi-navigation-label:focus[\s\S]*\.kpi-navigation-full-name[\s\S]*visibility: visible/, "keyboard focus reveals the full navigation label");
assert.match(page, /id="accountsWorkloadsSearchInput"[\s\S]*onInput=\{\(event\)[\s\S]*setSearchTerm\(search\)[\s\S]*onKeyDown=\{submitSearchOnEnter\}/, "search typing changes only the local draft and Enter submits");
assert.match(page, /id="accountsWorkloadsSearchButton"[\s\S]*aria-label="Search accounts and workloads"[\s\S]*onClick=\{submitSearch\}/, "accessible search icon button submits the server query");
assert.match(styles, /\.accounts-workloads-search__control\s*\{[^}]*display: flex[^}]*flex-wrap: nowrap/, "search input and button stay on one row at every viewport");
assert.match(styles, /\.accounts-workloads-search__control input\s*\{[^}]*flex: 1 1 auto[^}]*min-width: 0/, "search input can flex without forcing the button to wrap");
assert.match(styles, /\.accounts-workloads-search__control button\s*\{[^}]*flex: 0 0 auto/, "search button remains visible beside the flexible input");
assert.doesNotMatch(page, /onInput=\{\(event\) => \{[\s\S]{0,250}onQueryChange/, "search input does not query the server per keystroke");
assert.match(page, /toggleSort[\s\S]{0,350}onQueryChange\(\{ \.\.\.query, search: query\.search, includeDeleted/, "sorting preserves the last submitted search instead of submitting the draft");
assert.match(page, /nextIncludeDeleted[\s\S]{0,350}onQueryChange\(\{ \.\.\.query, search: query\.search, includeDeleted: nextIncludeDeleted/, "Include deleted preserves the last submitted search instead of submitting the draft");
assert.match(app, /handleAccountsWorkloadsRefresh[\s\S]*setAccountsWorkloadsRefreshing\(true\)[\s\S]*fetchAccountsWorkloads\(\{ fiscalYear, \.\.\.accountsWorkloadsQuery \}\)[\s\S]*setAccountsWorkloadsRows/, "Refresh re-fetches the lower table with the exact committed query");
assert.doesNotMatch(app, /handleAccountsWorkloadsRefresh[\s\S]{0,800}setAccountsWorkloadsLoading\(true\)/, "Refresh does not replace the whole page with initial loading state");
assert.doesNotMatch(app, /accountsWorkloadsRefreshVersion/, "Refresh does not replay the full-page loading effect");
assert.match(page, /accountsWorkloadsRefreshing[\s\S]*role="status"[\s\S]*Refreshing table/, "lower table exposes its own refresh pending state");
assert.match(app, /setKpiGuides\(\[\]\)[\s\S]*fetchKpiGuides\(fiscalYear\)/, "KPI Guide reload clears stale FY data before fetching");
assert.match(content, /guideRecords\.length === 0[\s\S]*getGuideDetails\(guide\)[\s\S]*setSavedGuideDetails\(authoritative\)[\s\S]*\}, \[guideRecords, fiscalYear\]\)/, "empty Guide responses reset child details to the current FY fallback");
assert.match(app, /fiscalYearRef[\s\S]*draft\.fiscalYear !== fiscalYearRef\.current[\s\S]*updateKpiGuide\(draft\)[\s\S]*fiscalYearRef\.current !== authoritative\.fiscalYear/, "late Guide saves cannot overwrite a different current FY");
assert.match(app, /setFxRate\(null\)[\s\S]*fetchFxRate\(fiscalYear\)/, "FX reload clears stale FY data before fetching");
assert.match(app, /fetchKpiGuides\(fiscalYear\)/, "opening the KPI Guide loads authoritative FY data");
assert.match(app, /updateKpiGuide\(draft\)/, "KPI Guide Save awaits the API adapter");
assert.match(app, /fetchFxRate\(fiscalYear\)/, "FY changes load the authoritative FX rate");
assert.doesNotMatch(page, /applyExchangeRate[\s\S]{0,500}(?:onSaveFxRate|updateFxRate|await)/, "FX Apply performs no API request");
assert.match(page, /applyExchangeRate[\s\S]*setExchangeRate\(parsed\)[\s\S]*arrKrw:[\s\S]*parsed[\s\S]*setAddingRow[\s\S]*acrKrw:[\s\S]*parsed[\s\S]*setIsDirty\(true\)/, "FX Apply updates the draft rate and recalculates table and add-row KRW values");
assert.match(page, /current\.map\(\(row\) => row\.isDeleted\s*\?\s*row\s*:/, "FX Apply leaves deleted rows unchanged so they are not emitted as stale active-row patches");
assert.match(page, /onRowsChange\(rowsToSave, permanentDeleteIds, draftFxRate\)/, "main Save sends row operations and optional FX in one adapter call");
assert.match(page, /const authoritative = await[\s\S]*setDraftRows\(authoritative\.items\)[\s\S]*authoritative\.fxRate/, "Save adopts authoritative rows and latest FX version");
assert.doesNotMatch(page, /Some changes were saved|Some rows were deleted permanently|Completed deletions were reconciled|partial/i, "atomic save errors never imply partial persistence");
assert.match(app, /saveAccountsWorkloadsBatch\(/, "App uses the atomic Accounts & Workloads batch adapter");
assert.doesNotMatch(app, /persistAndReconcileAccountWorkloadChanges\(/, "App no longer sequences row mutations");
assert.match(content, /id="kpiGuideLoading"[\s\S]*guideLoading/, "KPI Guide exposes a browser-checkable pending state");
assert.match(content, /id="kpiGuideError"[\s\S]*role="alert"/, "KPI Guide exposes an error state");
assert.match(content, /class="kpi-guide-dialog__body"/, "KPI Guide uses an app-owned scroll body");
assert.match(styles, /\.kpi-guide-dialog\s*\{[^}]*max-height: min\(92dvh, 58rem\)[^}]*display: flex[^}]*flex-direction: column/, "KPI Guide is constrained to the dynamic viewport");
assert.match(styles, /\.kpi-guide-dialog__body\s*\{[^}]*min-height: 0[^}]*overflow-y: auto/, "KPI Guide body owns vertical scrolling so Notes remain reachable");
assert.doesNotMatch(styles, /\.oj-dialog|\.oj-dialog-content|\.oj-dialog-body/, "KPI Guide scrolling does not override JET internal DOM");
assert.match(page, /id="accountsWorkloadsFxError"[\s\S]*role="alert"/, "FX exposes an error state");

console.log("accountsWorkloadsUiContract tests passed");
