import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { consumptionNavItems } from "../src/data/kpiMockData";
import { getNavigationRoute, getNavigationRouteFromPath } from "../src/components/navigationRoutes";

assert.deepEqual(consumptionNavItems.map((item) => item.label), ["Analysis", "Attainment", "Records"]);
assert.equal(consumptionNavItems[1].id, "attainment", "Attainment immediately follows Analysis");
assert.equal(getNavigationRoute("analysis").pageTitle, "Consumption Analysis");
assert.equal(getNavigationRoute("records").pageTitle, "Consumption Records");
assert.equal(getNavigationRoute("attainment").pageTitle, "Consumption Attainment");
assert.equal(getNavigationRoute("attainment").module, "consumptionAttainment");
assert.equal(getNavigationRouteFromPath("/attainment").id, "attainment");

const pageSource = readFileSync("src/components/content/AttainmentPage.tsx", "utf8");
const contentSource = readFileSync("src/components/content/index.tsx", "utf8");
assert.doesNotMatch(pageSource, /Pillar filter|Quarter filter/i, "Attainment keeps FY as its only global filter");
assert.match(pageSource, /Budget/);
assert.match(pageSource, /oj-dialog/);
assert.match(pageSource, /oj-chart/);
assert.match(pageSource, /seriesId: "Budget Target"/, "Quarter chart includes each quarter's budget target");
assert.match(pageSource, /seriesId: "Actual to date"/);
assert.match(pageSource, /seriesId: "Outlook \(Actual \+ Forecast\)"/);
assert.doesNotMatch(pageSource, /Forecast movement by quarter/i, "a non-movement chart does not claim to show movement");
assert.match(pageSource, /value\.toFixed\(0\).*K/, "Chart values are labeled in K without an additional unit conversion");
assert.doesNotMatch(pageSource, /referenceObjects: budgetReference/, "Quarter-varying budgets are data points, not one axis line");
assert.match(pageSource, /FY Total/);
assert.match(pageSource, /Outlook attainment/);
assert.match(pageSource, /vs budget/i);
assert.match(pageSource, /DP Actual/);
assert.match(pageSource, /DP Outlook/);
assert.match(pageSource, /OCI Actual/);
assert.match(pageSource, /OCI Outlook/);
assert.match(pageSource, /Account \/ Pillar/);
assert.match(pageSource, /Applied/);
assert.match(pageSource, /Not entered/);
assert.match(pageSource, /Closed months use Actual/);
assert.match(pageSource, /current and remaining months use Forecast/);
assert.match(pageSource, /Amounts in K/i, "Attainment communicates the K display unit");
assert.match(pageSource, /budget \(K\)/i, "Budget inputs explicitly use K units");
assert.doesNotMatch(pageSource, /scaling: "auto"/, "Chart must not compact already-K amounts into another unit");
assert.match(contentSource, /activeRoute\.module === "consumptionAttainment"[\s\S]*AttainmentPage/);

console.log("attainment UI contract tests passed");
