import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getNavigationRoute, getNavigationRouteFromPath } from "../src/components/navigationRoutes";
import { getFiscalYearForDate, getFiscalYearRange, getMonthCells, getDayKind } from "../src/data/calendarDateUtils";
import { getLocalRecordingKey, getRecordingCapability } from "../src/data/localRecordingStore";
import { canAccessLocalRecording } from "../src/data/meetingNotesApi";
import { failedCalendarFlagValue } from "../src/data/calendarUx";

assert.equal(getNavigationRoute("calendar").module, "calendar");
assert.equal(getNavigationRoute("meeting-notes").module, "meetingNotes");
assert.equal(getNavigationRouteFromPath("/calendar").id, "calendar");
assert.equal(getNavigationRouteFromPath("/meeting-notes").id, "meeting-notes");

assert.equal(getFiscalYearForDate("2025-05-31"), "FY25");
assert.equal(getFiscalYearForDate("2025-06-01"), "FY26");
assert.deepEqual(getFiscalYearRange("FY26"), { fromDate: "2025-06-01", toDate: "2026-05-31" });
const june = getMonthCells(2025, 5);
assert.equal(june.length, 42, "month view has a stable six-week grid");
assert.equal(june[0].date, "2025-06-01");
assert.equal(getDayKind("2025-06-01", new Map()), "sunday");
assert.equal(getDayKind("2025-06-07", new Map()), "saturday");
assert.equal(getDayKind("2025-06-06", new Map([["2025-06-06", "Memorial Day"]])), "holiday");

assert.deepEqual(getRecordingCapability({ hasMediaRecorder: false, hasGetUserMedia: true, isSecureContext: true, isMobile: false }),
  { supported: false, reason: "Recording is not supported by this browser." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: true }),
  { supported: false, reason: "Quick recording is unavailable on mobile. Use manual notes instead." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: false, isMobile: false }),
  { supported: false, reason: "Recording requires a secure browser context (HTTPS)." });
assert.equal(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: false }).supported, true);
assert.equal(getLocalRecordingKey(" user/a ", "51"), '["user/a","51"]', "local audio keys are scoped to the authenticated user");
assert.notEqual(getLocalRecordingKey("user/a", "51"), getLocalRecordingKey("user/b", "51"));
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/a"), true, "owners can access their local audio");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: true }, "user/b"), true, "explicit audio grants allow shared-note audio access");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/b"), false, "note text access does not imply audio access");

const navSource = readFileSync("src/data/kpiMockData.ts", "utf8");
assert.match(navSource, /id: "my-activities"[\s\S]*children: activityNavItems/);
assert.match(navSource, /id: "calendar", label: "Calendar"/);
assert.match(navSource, /id: "meeting-notes", label: "Meeting Notes"/);
const calendarSource = readFileSync("src/components/content/CalendarPage.tsx", "utf8");
const calendarApiSource = readFileSync("src/data/calendarApi.ts", "utf8");
const calendarStyles = readFileSync("src/styles/app.css", "utf8");
assert.match(calendarStyles, /\.calendar-timeline-event\.is-editable\s*\{[\s\S]*?touch-action:\s*none;/, "editable existing-event touch gestures opt out of native scrolling without trapping read-only events");
assert.match(calendarSource, /holidays\.get/);
assert.match(calendarSource, /PRIVATE[\s\S]*DETAILS/);
assert.doesNotMatch(calendarSource, /BUSY_ONLY/, "Calendar sharing no longer offers a busy-only scope");
assert.match(calendarSource, /const isInitialLoad = initialCalendarLoadRef\.current;[\s\S]*const finishBusy = isInitialLoad \? beginAppBusy\(\) : \(\) => undefined/, "only initial Calendar loading owns the global busy scope");
assert.match(calendarSource, /if \(isInitialLoad\) setCalendarLoading\(true\)[\s\S]*Promise\.all\(/, "only initial Calendar entry renders the loading state");
assert.match(calendarSource, /\.finally\(\(\) => \{[\s\S]*finishBusy\(\);[\s\S]*if \(active && isInitialLoad\)[\s\S]*setCalendarLoading\(false\);[\s\S]*initialCalendarLoadRef\.current = false;/, "only the active initial request closes initial local and global loading scopes");
assert.equal((calendarSource.match(/beginAppBusy\(\)/g) ?? []).length, 1, "Calendar initial loading has no duplicate busy scope");
assert.match(calendarSource, /onDblClick=\{\(\) => \{[\s\S]*openDay/, "desktop double click opens the selected day");
assert.match(calendarSource, /onDblClick=\{handleTimelineDoubleClick\}/, "desktop timeline double click creates a direct block draft");
assert.match(calendarSource, /lastTouchTapRef[\s\S]*setDayOpen\(true\)/, "mobile double tap opens the selected day");
assert.match(calendarSource, /const beginTimelineCreate[\s\S]*setTimeout[\s\S]*LONG_PRESS_CREATE_DELAY_MS/, "empty timeline creation uses the 500ms long-press contract");
assert.match(calendarSource, /longPressMovementCancels[\s\S]*preventDefault/, "movement cancels before activation and active dragging suppresses scrolling");
assert.match(calendarSource, /preventActivatedTouchScroll[\s\S]*creationPreviewRef\.current[\s\S]*touchmove[\s\S]*passive: false/, "activated mobile long-press uses a non-passive touch guard without blocking pre-activation scroll");
assert.match(calendarSource, /calendar-day-undated[\s\S]*calendar-create-row-preview/, "dragging into the shared top lane renders its row preview");
assert.match(calendarSource, /dayOpen && <oj-c-dialog[\s\S]*dialogTitle=\{selectedDate\}[\s\S]*calendar-day-dialog[\s\S]*calendar-day-detail/, "the selected-day timeline is contained by one JET modal dialog");
assert.match(calendarSource, /import "oj-c\/dialog"/);
assert.match(calendarSource, /import "oj-c\/popup"/);
assert.match(calendarSource, /calendar-editor-options-launcher[\s\S]*<oj-c-popup[\s\S]*calendar-options-popover/, "event options use a JET popup");
assert.match(calendarSource, /calendar-color-[\s\S]*<oj-c-popup[\s\S]*calendar-legend__palette/, "legend colors use a JET popup");
assert.match(calendarSource, /calendar-day-timeline--interactive/);
assert.match(calendarSource, /calendar-timeline-editor[\s\S]*renderDraftEditor/, "timed editing is rendered inside its timeline block");
assert.match(calendarSource, /class="calendar-block-editor__title"/, "the blue event block itself owns the direct title input");
const blockEditorStart = calendarSource.indexOf("const renderDraftEditor");
const blockEditorEnd = calendarSource.indexOf("const eventColor", blockEditorStart);
const blockEditorSource = calendarSource.slice(blockEditorStart, blockEditorEnd);
assert.ok(blockEditorStart >= 0 && blockEditorEnd > blockEditorStart, "block editor source is discoverable");
assert.doesNotMatch(blockEditorSource, /class="calendar-event-form"/, "no create or edit path may render the legacy multi-field event form");
assert.doesNotMatch(blockEditorSource, />From</, "the block editor has no separate From field");
assert.doesNotMatch(blockEditorSource, />To</, "the block editor has no separate To field");
assert.match(calendarSource, /calendar-day-blank-row/, "the combined all-day and unspecified lane retains a consecutive-entry row");
assert.doesNotMatch(calendarSource, /<section class="calendar-inline-editor"/, "there is no separate editor below the calendar");
assert.match(calendarSource, /onCompositionStart[\s\S]*onCompositionEnd/, "inline title save is IME-safe");
assert.match(calendarSource, /event\.isComposing/, "Enter is ignored while the browser reports active IME composition");
const titleMentionEffectStart = calendarSource.indexOf("const trigger = draft ? extractTitleSearchTrigger");
const titleMentionEffectEnd = calendarSource.indexOf("\n  useEffect(() => {\n    if (!mentionEditing)", titleMentionEffectStart);
const titleMentionEffect = calendarSource.slice(titleMentionEffectStart, titleMentionEffectEnd);
assert.match(titleMentionEffect, /setTitleSearchOpen\(true\)/, "the mention result area opens while the debounced search is pending");
assert.match(titleMentionEffect, /setTimeout\([\s\S]*250\)/, "related-item search is debounced without making title typing wait");
assert.match(titleMentionEffect, /listCalendarRelatedItems\(lookupFiscalYear, trigger\.query, 0\)/, "@ search reuses KPI workload-options without a Calendar-only FY filter");
assert.match(titleMentionEffect, /requestIsLatest/, "stale related mention search responses are discarded");
assert.match(titleMentionEffect, /setTimeout\([\s\S]*listSharingUsers\(trigger\.query\)/, "# participant lookup is separated from immediate title input");
assert.match(calendarSource, /setTitleSearchError\("Could not load search results\. Please try again\."\)/, "title search failures are visible inside the inline search region");
assert.match(calendarSource, /setMentionSearchError\("Could not load search results\. Please try again\."\)/, "editable mention search failures are visible inside the mention search region");
assert.match(calendarSource, /class="calendar-inline-search__error" role="alert"/, "inline search errors use an accessible local alert rather than the global busy overlay");
assert.match(calendarSource, /mentionEditing\.kind === "related"[\s\S]*setMentionRelatedOptions\(\[\]\)[\s\S]*listCalendarRelatedItems/, "a new @ request hides stale account, workload, and opportunity choices before loading");
assert.match(calendarSource, /setMentionUserOptions\(\[\]\)[\s\S]*listSharingUsers\(mentionQuery\)/, "a new # request hides stale user choices before loading");
assert.match(calendarSource, /relatedItemType: item\.type[\s\S]*relatedItemId: String\(item\.id\)/, "Calendar stores the selected account, workload, or opportunity as an explicit relationship");
assert.match(calendarSource, /setDraft\(\{ \.\.\.draft, \.\.\.applyRelatedSelection\(draft\.title, item\) \}\)/, "selecting an @ result applies the selected related-item keys to the draft");
assert.match(calendarSource, /titleInputRef\.current\?\.focus\(\)[\s\S]*setSelectionRange/, "mention selection restores the title cursor");
assert.match(calendarSource, /event\.key === "ArrowDown"[\s\S]*event\.key === "ArrowUp"[\s\S]*event\.key === "Escape"/, "mention popover supports arrow navigation and escape");
assert.match(calendarSource, /Weekly Activities/);
assert.match(calendarSource, /fetchWeeklyActivities/);
assert.match(calendarSource, /calendar-event__text/);
assert.doesNotMatch(calendarSource, /title=\{text\}/, "event tooltip is not rendered unconditionally");
assert.match(calendarSource, /Reopen Event[\s\S]*Cancel Event[\s\S]*Delete/, "event mutation icons use English labels");
assert.match(calendarSource, /timeUnknown: true/, "new events start without a designated time");
assert.doesNotMatch(calendarSource, /applyRelatedSelection\("", item\)/, "relation selection never empties or rewrites the pure title");
assert.match(calendarSource, /const eventDisplayTitle = \(event: CalendarEvent\) => event\.title;/, "the first line remains the pure saved title");
assert.doesNotMatch(calendarSource, /titleWithAccountPrefix/, "legacy account prefixes cannot return to event titles");
assert.match(calendarSource, /permission: "VIEW"[\s\S]*visibility: "DETAILS"/, "# selection stores a VIEW / DETAILS event share");
assert.match(calendarSource, /setSelectedEventId\(saved\.id\)[\s\S]*setSelectedDate\(eventCalendarDate\(saved\.startsAt/, "a created event immediately adopts its real API id and remains selectable");
assert.match(calendarSource, /const selectEvent = \(event: CalendarEvent\)[\s\S]*setSelectedEventId\(event\.id\)/, "selection is independent from opening edit mode");
assert.match(calendarSource, /selectedEventId === event\.id \? " is-selected"/, "month and timeline representations share one selected event id");
assert.match(calendarSource, /selectedTimelineActions[\s\S]*title="Recurrence"[\s\S]*Private:[\s\S]*Time Off:[\s\S]*Cancel Event[\s\S]*title="Delete"/, "timeline selection exposes recurrence, private, Time Off, cancel and delete icons");
assert.match(calendarSource, /selectedCalendarActions[\s\S]*Private:[\s\S]*Time Off:[\s\S]*Cancel Event[\s\S]*title="Delete"/, "calendar selection exposes immediate private, Time Off, cancel and delete icons");
assert.doesNotMatch(calendarSource, /calendar-event-actions__readonly/, "shared events do not render a Read Only label");
assert.match(calendarSource, /onDblClick=\{\(click\)[\s\S]*openEdit\(event\)/, "calendar double-click opens the timeline for owned and shared events");
assert.match(calendarSource, /class="calendar-event__title" onDblClick=[\s\S]*beginTitleEdit\(event\)/, "timeline title double-click alone enters title editing");
assert.match(calendarSource, /cancelBehavior="icon"/, "JET day dialog renders its close X in the date header");
assert.doesNotMatch(calendarSource, /calendar-day-dialog__hint/, "timeline guidance and interval copy are removed");
assert.match(calendarSource, /ModalStyles_backdropScrimStyle[\s\S]*requestDayClose\(\)/, "clicking the rendered JET backdrop uses the same protected close path");
assert.match(calendarSource, /onojClose=\{requestDayClose\}/, "all JET day-dialog close paths pass through unsaved-change protection");
assert.match(calendarSource, /if \(draft\) \{ event\.preventDefault\(\); requestDayClose\(\); \}/, "Escape uses unsaved-change protection for new and existing drafts");
assert.match(calendarSource, /editorBaselineRef\.current = \{ draft: \{ \.\.\.next \}, shares: \[\] \}/, "new-event dirty detection compares every editable field to the editor baseline");
assert.match(calendarSource, /editorBaselineRef\.current = \{ draft: \{ \.\.\.savedDraft \}, shares: \[\.\.\.eventShares\] \}/, "successful inline persistence advances the dirty baseline");
assert.match(calendarSource, /Save and close[\s\S]*Discard and close[\s\S]*Keep editing|Keep editing[\s\S]*Discard and close[\s\S]*Save and close/, "dirty close offers save, discard, or continued editing");
assert.match(calendarSource, /editorBaselineRef[\s\S]*JSON\.stringify\(toInput\(draft, eventShares\)\)[\s\S]*JSON\.stringify\(toInput\(baseline\.draft, baseline\.shares\)\)/, "new and existing event close protection compares every persisted draft field and participant against the editor baseline");
assert.match(calendarSource, /openCreate[\s\S]*hasUnsavedChanges\(\)[\s\S]*setCloseConfirmOpen\(true\)/, "starting another event cannot silently replace an unsaved draft");
assert.match(calendarSource, /openEventSettings[\s\S]*editing\?\.id !== event\.id[\s\S]*hasUnsavedChanges\(\)/, "settings cannot silently replace edits for another event");
assert.match(calendarSource, /beginTitleEdit[\s\S]*editing\?\.id !== event\.id[\s\S]*hasUnsavedChanges\(\)/, "double-click edit cannot silently replace edits for another event");
assert.match(calendarSource, /updateCalendarEventEntity\(editing, input\)[\s\S]*setEditing\(persisted\)[\s\S]*syncCalendarEventShares\(persisted/, "a persisted event version is retained before share synchronization so failed saves can be retried");
assert.match(calendarSource, /const applySettings[\s\S]*updateCalendarEventEntity\(editing[\s\S]*editorBaselineRef\.current = \{ draft: \{ \.\.\.persistedDraft \}, shares: \[\.\.\.previousShares\] \}[\s\S]*syncCalendarEventShares\(persisted, eventShares, undefined, previousShares\)[\s\S]*shares: \[\.\.\.saved\.shares\]/, "settings persistence never marks unsynchronized participant changes clean and retains the latest entity version on share failure");
assert.match(calendarSource, /calendar-event-actions[\s\S]*onKeyDown=\{\(key\) => key\.stopPropagation\(\)\}/, "selected-event actions preserve keyboard activation without bubbling into the event selector");
assert.match(calendarSource, /#Participants[\s\S]*Add participant/, "# is presented as an event participant rather than Calendar sharing");
assert.doesNotMatch(calendarSource, /share\.displayName \?\? share\.userKey/, "opaque participant GUIDs are never used as display labels");
assert.match(calendarApiSource, /share\.displayName \? \{ displayName: share\.displayName \} : \{\}/, "participant display names returned by the API survive DTO mapping");
assert.match(calendarSource, /onScroll=\{handleTitleSearchScroll\}/, "account search loads the next page at the bottom of the result scroller");
assert.match(calendarSource, /page\.items\.filter\([\s\S]*existing\.type === item\.type && existing\.id === item\.id/, "incremental account pages deduplicate results");
assert.match(calendarStyles, /\.calendar-timeline-event__time[\s\S]*order:\s*-2/, "timeline time is rendered above the title");
assert.match(calendarStyles, /\.calendar-timeline-event[\s\S]*font-size:\s*\.68rem[\s\S]*overflow:\s*hidden/, "one-hour blocks use compact clipped typography");
assert.match(calendarStyles, /\.calendar-weekly-popup__box[\s\S]*border:/, "this-week and next-week content remains inside bordered grid boxes");
assert.match(calendarSource, /calendar-event-relations[\s\S]*`@\$\{draftAccountName\}`/, "stored account relation renders as a separate @accountName mention");
assert.match(calendarSource, /const participants = event\.shares\.map[\s\S]*>#\{participants\.join\(","\)\}/, "stored event shares render as one comma-separated #displayName mention");
assert.match(calendarSource, /class="calendar-event-relations"/, "relationship mentions occupy their own event line");
assert.match(calendarSource, /event\.canEdit \? <button[\s\S]*setMentionEditing/, "owners can edit relation mentions directly from view state");
assert.match(calendarSource, /updateCalendarEvent\(event, toInput\(nextDraft, shares\)\)/, "direct mention edits persist relation and exact replacement/removal shares");
assert.match(calendarSource, /Change My Events color[\s\S]*Change Private color[\s\S]*Change Cancelled color/, "all fixed legend entries expose color buttons");
assert.match(calendarSource, /direction === "OUTGOING"[\s\S]*status === "ACCEPTED"/, "accepted outgoing requests expose the shared owner to the viewing requester");
assert.match(calendarSource, /getCalendarDisplayPreferences[\s\S]*changeCalendarDisplayPreference/, "viewer colors are persisted through authenticated APIs");
assert.match(calendarSource, /CALENDAR_SHARE_COLORS\.map[\s\S]*Custom color/, "legend palette exposes Redwood colors and custom input");
assert.match(calendarSource, /dangerouslySetInnerHTML=\{\{ __html: sanitizeWeeklyActivityHtml/, "weekly popup HTML passes through the shared allow-list sanitizer");
assert.match(calendarSource, /beginResize[\s\S]*resizeTimelineRange/, "vertical pointer resizing uses the one-hour-minimum range helper");
const beginResizeSource = calendarSource.slice(calendarSource.indexOf("const beginResize"), calendarSource.indexOf("const beginMove"));
const beginMoveSource = calendarSource.slice(calendarSource.indexOf("const beginMove"), calendarSource.indexOf("const beginExistingEventGesture"));
assert.match(beginResizeSource, /const captureTarget = document\.documentElement;/);
assert.match(calendarSource, /const existingGesturePointerIdRef = useRef<number \| null>\(null\)/, "existing event gestures remember the first active pointer");
assert.match(beginResizeSource, /if \(existingGesturePointerIdRef\.current !== null\) return;/, "resize ignores another pointer while active");
assert.match(beginResizeSource, /if \(existingGesturePointerIdRef\.current === pointerId\) existingGesturePointerIdRef\.current = null;/, "resize cleanup releases the active pointer slot");
assert.match(beginResizeSource, /captureTarget\.setPointerCapture\(pointerId\)/);
assert.match(beginResizeSource, /captureTarget\.releasePointerCapture\(pointerId\)/);
assert.match(beginResizeSource, /pointercancel/);
assert.match(beginResizeSource, /passive: false/, "existing-event resize captures one pointer on the stable timeline and cleans up cancelled gestures");
assert.match(calendarSource, /calendar-resize-handle--start[\s\S]*calendar-resize-handle--end/, "both timeline edges expose resize handles");
assert.match(calendarSource, /titleEditing \|\| !editing \? <input[\s\S]*<EventTitle text=\{draft\.title/, "new events use an input while single selection keeps an existing title in view state until explicit editing");
assert.match(calendarSource, /onDblClick=\{\(click\)[\s\S]*beginTitleEdit\(event\)/, "desktop double-click enters title editing");
assert.match(calendarSource, /lastEventTitleTouchRef[\s\S]*previous\?\.eventId === event\.id[\s\S]*beginTitleEdit\(event\)/, "mobile double-tap survives the event-to-editor remount and enters title editing");
const editorActions = calendarSource.slice(calendarSource.indexOf('id="calendar-editor-options-launcher"'), calendarSource.indexOf('</span>', calendarSource.indexOf('id="calendar-editor-options-launcher"')));
const actionPositions = ['aria-label="Recurrence"', 'aria-label="Save"', 'aria-label="Cancel editing"', '"Cancel Event"', '>Delete</button>'].map((token) => editorActions.indexOf(token));
assert.ok(actionPositions.every((position) => position >= 0) && actionPositions.every((position, index) => index === 0 || actionPositions[index - 1] < position), "selection and edit action order distinguishes edit cancel from event cancel");
assert.match(calendarSource, /autoDismiss="none"[\s\S]*onojClose=\{closeSettings\}/, "settings owns its close state instead of racing the launcher click");
assert.match(calendarSource, /if \(!editorMenuOpen\) return;[\s\S]*#calendar-editor-options-launcher, \[aria-label='Recurrence'\][\s\S]*closeSettings\(\)[\s\S]*document\.addEventListener\("pointerdown", handleOutsideSettings, true\)/, "recurrence closes on outside pointer interaction but not on launcher or popup interaction");
assert.match(calendarSource, /aria-label="Recurrence"[\s\S]*Repeat until[\s\S]*Working days[\s\S]*void applySettings\(\)[\s\S]*>Apply</, "recurrence popup includes repeat and working-day controls only");
assert.match(calendarSource, /const \[settingsDraft, setSettingsDraft\][\s\S]*const closeSettings = \(\) => \{ setEditorMenuOpen\(false\); setSettingsDraft\(null\); \}/, "dismissed settings are discarded independently of the main event draft");
assert.match(calendarSource, /if \(!editing\) \{[\s\S]*setDraft\(nextDraft\)[\s\S]*closeSettings\(\)/, "new-event settings commit locally without requiring an existing event version");
assert.match(calendarSource, /\(titleEditing \|\| !editing\) && editable[\s\S]*aria-label="Save"[\s\S]*\(titleEditing \|\| !editing\)[\s\S]*aria-label="Cancel editing"/, "new events expose visible Save and Cancel actions");
assert.doesNotMatch(calendarSource, /No additional description/, "empty-description placeholder is not duplicated above the event editor");
assert.match(calendarSource, /event\.allDay \? "▣" : event\.timeUnknown \? "◷" : shared \? "↗"/, "month events render exactly one priority icon for all-day, unspecified-time, or participant state");
assert.doesNotMatch(calendarSource, /calendar-event__kind/, "month events do not duplicate the type icon");
assert.match(calendarSource, /beginMove[\s\S]*onPointerDown=\{\(pointer\) => beginExistingEventGesture/, "timeline blocks support direct pointer movement through touch-aware hit testing");
assert.match(beginMoveSource, /const captureTarget = document\.documentElement;/);
assert.match(beginMoveSource, /captureTarget\.setPointerCapture\(pointerId\)/);
assert.match(beginMoveSource, /captureTarget\.releasePointerCapture\(pointerId\)/);
assert.match(beginMoveSource, /pointercancel/);
assert.match(beginMoveSource, /passive: false/, "existing-event movement captures one pointer on the stable timeline and cleans up cancelled gestures");
assert.match(beginMoveSource, /if \(existingGesturePointerIdRef\.current !== null\) return;/, "move ignores another pointer while active");
assert.match(beginMoveSource, /if \(next\.pointerId !== pointerId\) return;/, "move ignores events from another pointer");
assert.match(beginMoveSource, /Math\.max\(MIN_CALENDAR_DURATION_MINUTES, originalEnd - originalStart\)/, "move preserves at least a sixty-minute event duration");
assert.match(beginResizeSource, /originalEnd - MIN_CALENDAR_DURATION_MINUTES/, "start resize enforces the sixty-minute minimum");
assert.match(calendarSource, /const beginDraftGesture[\s\S]*Math\.max\(MIN_CALENDAR_DURATION_MINUTES, originEnd - originStart\)[\s\S]*originEnd - MIN_CALENDAR_DURATION_MINUTES[\s\S]*originStart \+ MIN_CALENDAR_DURATION_MINUTES/, "open editor move and resize enforce the sixty-minute minimum");
const beginDraftGestureSource = calendarSource.slice(calendarSource.indexOf("const beginDraftGesture"), calendarSource.indexOf("const persistTimelineRange"));
assert.match(beginDraftGestureSource, /updateCalendarEvent\(editing, toInput\(latestDraft, eventShares\)\)/, "selected-editor move and resize persist their changed time without requiring title editing");
assert.match(beginDraftGestureSource, /const savedDraft = draftFromEvent\(saved\)[\s\S]*setEditing\(saved\)[\s\S]*setDraft\(savedDraft\)/, "selected-editor time persistence refreshes the event version and canonical draft");
assert.match(calendarSource, /const lookupFiscalYear = getFiscalYearForDate\(draft!\.startDate\)/, "title related-item lookup follows the edited event fiscal year");
assert.match(calendarSource, /listCalendarRelatedItems\(getFiscalYearForDate\(date\), mentionQuery, 0\)/, "selected-event relation lookup sends the event fiscal year through the shared KPI contract");
assert.doesNotMatch(calendarSource, /currentTarget\.setPointerCapture/, "the event node removed by openEdit never owns pointer capture");
assert.match(calendarSource, /const beginExistingEventGesture[\s\S]*pointerType !== "touch"[\s\S]*compactResizeRailStart[\s\S]*"start"[\s\S]*"end"/, "compact touch events reserve a side rail for resize while keeping a practical move surface");
assert.match(calendarSource, /is-touch-compact/, "short events expose explicit compact touch geometry");
assert.match(calendarStyles, /\.calendar-timeline-event\.is-touch-compact \.calendar-resize-handle[\s\S]*width:\s*44px/, "compact resize handles stay finger-addressable without consuming the whole event width");
assert.match(calendarSource, /suppressExistingClickUntilRef[\s\S]*performance\.now\(\) \+ 500[\s\S]*click\.preventDefault\(\)/, "touch completion suppresses the synthetic click that would restore stale event times");
assert.match(calendarSource, /persistTimelineRange[\s\S]*updateCalendarEventEntity/, "drag and resize persist directly without opening the editor");
assert.doesNotMatch(beginResizeSource, /openEdit\(event\)/, "resize never opens the editor");
assert.doesNotMatch(beginMoveSource, /openEdit\(event\)/, "drag never opens the editor");
assert.match(calendarSource, /onDblClick=\{[\s\S]*onEdit\?\.\(\)/, "the title component exposes desktop double-click editing");
assert.match(calendarSource, /<EventTitle text=\{draft\.title\} onEdit=\{\(\) => editing && beginTitleEdit\(editing\)\}/, "only explicit title activation enters title editing for a selected event");
assert.match(calendarSource, /calendar-event__full-title[\s\S]*role="tooltip"/, "truncated event titles expose an accessible full-content tooltip");
assert.match(calendarSource, /ownerDisplayName/, "shared calendar source owner is rendered separately from recipients");
assert.match(calendarSource, /vacation[\s\S]*recurrence[\s\S]*workingDays/, "Time Off and recurrence fields are available in the direct editor");
assert.match(calendarSource, /Repeat until[\s\S]*type="date"[\s\S]*<label>Working days[\s\S]*type="number"/, "recurring events collect the required end date and every event can collect a numeric working-day duration");
assert.match(calendarSource, /settingsDraft\.recurrence !== "NONE"[\s\S]*Repeat until[\s\S]*<label>Working days/, "working-day duration remains available when recurrence is NONE");
assert.match(calendarSource, /calendar-undated-kind/, "all-day and unspecified events expose differentiated type marks");
assert.match(calendarSource, /setDraftColor[\s\S]*>Apply</, "legend color changes remain draft-only until Apply");
assert.match(calendarSource, /calendar-weekly-popup__box[\s\S]*This Week[\s\S]*calendar-weekly-popup__box[\s\S]*Next Week/, "weekly activities use separate boxes");
assert.doesNotMatch(calendarSource, /calendar-day__add/);
const notesSource = readFileSync("src/components/content/MeetingNotesPage.tsx", "utf8");
assert.match(notesSource, /Raw audio stays on this device and browser only/);
assert.match(notesSource, /I have everyone’s consent to record/);
assert.match(notesSource, /external AI is not configured/i);
assert.match(notesSource, /codexConnectionPrimaryLabel\(codexConnection\)/);
assert.match(notesSource, /codex-connection-notice/);
assert.match(notesSource, /개인별 Codex 연결은 현재 지원되지 않습니다/);
assert.match(notesSource, /calendarEventId: event\.id[\s\S]*accountId: event\.accountId/);
assert.match(notesSource, /never exposed through event sharing/);
assert.match(notesSource, /permission-error/);
assert.match(notesSource, /interrupted/);
assert.match(notesSource, /save-error/);
assert.match(notesSource, /Share settings were not fully synchronized/);
assert.match(notesSource, /Retry sharing/);
assert.match(notesSource, /canAccessLocalRecording/);
const calendarCss = readFileSync("src/styles/app.css", "utf8");
assert.match(calendarCss, /\.calendar-page-card\s*\{/);
assert.match(calendarCss, /\.calendar-event__text\s*\{[^}]*text-overflow:\s*ellipsis/);
assert.match(calendarCss, /\.calendar-day-timeline--interactive\s*\{/);
assert.match(calendarSource, /calendar-day-timeline-scroll[\s\S]*calendar-day-timeline--interactive/, "the fixed day header and undated lane sit outside the only scrolling timeline viewport");
assert.match(calendarCss, /\.calendar-day-timeline-scroll\s*\{[^}]*overflow-y:\s*auto/, "only the timeline viewport scrolls vertically");
assert.match(calendarCss, /\.kpi-shell:has\(\.calendar-page\) \.kpi-footer\s*\{[^}]*position:\s*static/, "the shared footer cannot cover Calendar rows");
assert.match(calendarSource, /eventMutationQueueRef[\s\S]*previousRequest[\s\S]*eventServerStateRef[\s\S]*isLatestEventMutation/, "rapid saved-event flag mutations are serialized and stale responses cannot overwrite the latest UI state");
assert.match(calendarSource, /eventMutationKey = \(eventId: number, field: "forcePrivate" \| "vacation"\)/, "Private and Time Off keep independent latest-request identities");
assert.match(calendarSource, /nextEventMutationSeq\(event\.id, flag\)[\s\S]*isLatestEventMutation\(event\.id, flag, sequence\)/, "each flag retains its own rollback sequence while same-event writes remain serialized");
assert.match(calendarSource, /confirmedValue = eventServerStateRef\.current\.get\(event\.id\)\?\.\[flag\][\s\S]*failedCalendarFlagValue\(confirmedValue, previousValue\)/, "the latest failure rolls back to server-confirmed state rather than another optimistic value");
assert.equal(failedCalendarFlagValue(false, true), false, "both writes failing returns UI to the original server value");
assert.equal(failedCalendarFlagValue(true, false), true, "first success followed by second failure returns UI to the first confirmed server value");
assert.equal(failedCalendarFlagValue(false, true), false, "first failure followed by second success leaves UI at the second confirmed server value");
assert.match(calendarSource, /change reverted/, "failed optimistic flag changes visibly roll back");
assert.match(calendarCss, /\.calendar-day\.is-selected\s*\{\s*background:/, "selection is a subtle background, not a red border");
assert.match(calendarCss, /\.calendar-day:focus-visible/, "keyboard focus remains independently visible");
const contentSource = readFileSync("src/components/content/index.tsx", "utf8");
assert.match(contentSource, /recordingNamespace=\{profile\.userKey\}/);

console.log("calendar and meeting notes tests passed");
