import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getNavigationRoute, getNavigationRouteFromPath } from "../src/components/navigationRoutes";
import { getFiscalYearForDate, getFiscalYearRange, getMonthCells, getDayKind } from "../src/data/calendarDateUtils";
import { getLocalRecordingKey, getRecordingCapability } from "../src/data/localRecordingStore";
import { canAccessLocalRecording } from "../src/data/meetingNotesApi";

assert.equal(getNavigationRoute("calendar").module, "calendar");
assert.equal(getNavigationRoute("meeting-notes").module, "meetingNotes");
assert.equal(getNavigationRouteFromPath("/calendar").id, "calendar");
assert.equal(getNavigationRouteFromPath("/meeting-notes").id, "meeting-notes");

assert.equal(getFiscalYearForDate("2025-05-31"), "FY25");
assert.equal(getFiscalYearForDate("2025-06-01"), "FY26");
assert.deepEqual(getFiscalYearRange("FY26"), { fromDate: "2025-06-01", toDate: "2026-05-31" });
const june = getMonthCells(2025, 5);
assert.equal(june.length, 42, "month view has a stable six-week grid");
assert.equal(june[0].date, "2025-06-01");
assert.equal(getDayKind("2025-06-01", new Map()), "sunday");
assert.equal(getDayKind("2025-06-07", new Map()), "saturday");
assert.equal(getDayKind("2025-06-06", new Map([["2025-06-06", "Memorial Day"]])), "holiday");

assert.deepEqual(getRecordingCapability({ hasMediaRecorder: false, hasGetUserMedia: true, isSecureContext: true, isMobile: false }),
  { supported: false, reason: "Recording is not supported by this browser." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: true }),
  { supported: false, reason: "Quick recording is unavailable on mobile. Use manual notes instead." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: false, isMobile: false }),
  { supported: false, reason: "Recording requires a secure browser context (HTTPS)." });
assert.equal(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: false }).supported, true);
assert.equal(getLocalRecordingKey(" user/a ", "51"), '["user/a","51"]', "local audio keys are scoped to the authenticated user");
assert.notEqual(getLocalRecordingKey("user/a", "51"), getLocalRecordingKey("user/b", "51"));
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/a"), true, "owners can access their local audio");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: true }, "user/b"), true, "explicit audio grants allow shared-note audio access");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/b"), false, "note text access does not imply audio access");

const navSource = readFileSync("src/data/kpiMockData.ts", "utf8");
assert.match(navSource, /id: "my-activities"[\s\S]*children: activityNavItems/);
assert.match(navSource, /id: "calendar", label: "Calendar"/);
assert.match(navSource, /id: "meeting-notes", label: "Meeting Notes"/);
const calendarSource = readFileSync("src/components/content/CalendarPage.tsx", "utf8");
assert.match(calendarSource, /holidays\.get/);
assert.match(calendarSource, /PRIVATE[\s\S]*DETAILS/);
assert.doesNotMatch(calendarSource, /BUSY_ONLY/, "Calendar sharing no longer offers a busy-only scope");
assert.match(calendarSource, /onDblClick=\{\(\) => \{[\s\S]*openDay/, "desktop double click opens the selected day");
assert.match(calendarSource, /lastTouchTapRef[\s\S]*setDayOpen\(true\)/, "mobile double tap opens the selected day");
assert.match(calendarSource, /const beginTimelineCreate[\s\S]*setTimeout[\s\S]*LONG_PRESS_CREATE_DELAY_MS/, "empty timeline creation uses the 500ms long-press contract");
assert.match(calendarSource, /longPressMovementCancels[\s\S]*preventDefault/, "movement cancels before activation and active dragging suppresses scrolling");
assert.match(calendarSource, /calendar-day-undated[\s\S]*calendar-create-row-preview/, "dragging into the shared top lane renders its row preview");
assert.match(calendarSource, /dayOpen && <oj-c-dialog[\s\S]*dialogTitle=\{selectedDate\}[\s\S]*calendar-day-dialog[\s\S]*calendar-day-detail/, "the selected-day timeline is contained by one JET modal dialog");
assert.match(calendarSource, /import "oj-c\/dialog"/);
assert.match(calendarSource, /import "oj-c\/popup"/);
assert.match(calendarSource, /calendar-editor-options-launcher[\s\S]*<oj-c-popup[\s\S]*calendar-options-popover/, "event options use a JET popup");
assert.match(calendarSource, /calendar-color-[\s\S]*<oj-c-popup[\s\S]*calendar-legend__palette/, "legend colors use a JET popup");
assert.match(calendarSource, /calendar-day-timeline--interactive/);
assert.match(calendarSource, /calendar-timeline-editor[\s\S]*renderDraftEditor/, "timed editing is rendered inside its timeline block");
assert.match(calendarSource, /calendar-day-blank-row/, "the combined all-day and unspecified lane retains a consecutive-entry row");
assert.doesNotMatch(calendarSource, /<section class="calendar-inline-editor"/, "there is no separate editor below the calendar");
assert.match(calendarSource, /onCompositionStart[\s\S]*onCompositionEnd/, "inline title save is IME-safe");
assert.match(calendarSource, /event\.isComposing/, "Enter is ignored while the browser reports active IME composition");
const titleMentionEffect = calendarSource.slice(calendarSource.indexOf("const trigger = draft ? extractTitleSearchTrigger"), calendarSource.indexOf("if (!mentionEditing) return"));
assert.match(titleMentionEffect, /setTitleSearchOpen\(true\)/, "the mention result area opens immediately");
assert.doesNotMatch(titleMentionEffect, /setTimeout/, "mention search is immediate rather than artificially delayed");
assert.match(titleMentionEffect, /listCalendarRelatedItems\(lookupFiscalYear, trigger\.query\)/, "@ related-item search calls the directory immediately");
assert.match(titleMentionEffect, /listSharingUsers\(trigger\.query\)/, "# sharing-user search calls the directory immediately");
assert.match(titleMentionEffect, /requestIsLatest/, "stale mention search responses are discarded");
assert.match(calendarSource, /titleInputRef\.current\?\.focus\(\)[\s\S]*setSelectionRange/, "mention selection restores the title cursor");
assert.match(calendarSource, /event\.key === "ArrowDown"[\s\S]*event\.key === "ArrowUp"[\s\S]*event\.key === "Escape"/, "mention popover supports arrow navigation and escape");
assert.match(calendarSource, /Weekly Activities/);
assert.match(calendarSource, /fetchWeeklyActivities/);
assert.match(calendarSource, /calendar-event__text/);
assert.doesNotMatch(calendarSource, /title=\{text\}/, "event tooltip is not rendered unconditionally");
assert.match(calendarSource, /일정 다시 열기[\s\S]*일정 취소[\s\S]*일정 삭제/);
assert.match(calendarSource, /timeUnknown: true/, "new events start without a designated time");
assert.match(calendarSource, /applyRelatedSelection\("", item\)/, "related selection persists metadata without inserting it into the title");
assert.match(calendarSource, /eventDisplayTitle\(event\)/, "saved Workload and Opportunity events display their parent account before the title");
assert.match(calendarSource, /permission: "VIEW"[\s\S]*visibility: "DETAILS"/, "# selection stores a VIEW / DETAILS event share");
assert.match(calendarSource, /calendar-event-relations[\s\S]*`@\$\{draftAccountName\}`/, "stored account relation renders as a separate @accountName mention");
assert.match(calendarSource, /eventShares\.map[\s\S]*>#\{sharingUsers\.find/, "stored event shares render as separate #displayName mentions");
assert.match(calendarSource, /class="calendar-event-relations"/, "relationship mentions occupy their own event line");
assert.match(calendarSource, /event\.canEdit \? <button[\s\S]*setMentionEditing/, "owners can edit relation mentions directly from view state");
assert.match(calendarSource, /updateCalendarEvent\(event, toInput\(nextDraft, shares\)\)/, "direct mention edits persist relation and exact replacement/removal shares");
assert.match(calendarSource, /내 일정 색상 변경[\s\S]*비공개 색상 변경[\s\S]*취소됨 색상 변경/, "all fixed legend entries expose color buttons");
assert.match(calendarSource, /direction === "OUTGOING"[\s\S]*status === "ACCEPTED"/, "accepted outgoing requests expose the shared owner to the viewing requester");
assert.match(calendarSource, /getCalendarDisplayPreferences[\s\S]*changeCalendarDisplayPreference/, "viewer colors are persisted through authenticated APIs");
assert.match(calendarSource, /CALENDAR_SHARE_COLORS\.map[\s\S]*Custom 색상/, "legend palette exposes Redwood colors and custom input");
assert.match(calendarSource, /dangerouslySetInnerHTML=\{\{ __html: sanitizeWeeklyActivityHtml/, "weekly popup HTML passes through the shared allow-list sanitizer");
assert.match(calendarSource, /beginResize[\s\S]*resizeTimelineRange/, "vertical pointer resizing uses the ten-minute range helper");
assert.match(calendarSource, /calendar-resize-handle--start[\s\S]*calendar-resize-handle--end/, "both timeline edges expose resize handles");
assert.match(calendarSource, /beginMove[\s\S]*onPointerDown=\{\(pointer\) => beginMove/, "timeline blocks support direct pointer movement");
assert.match(calendarSource, /setDraftColor[\s\S]*>적용</, "legend color changes remain draft-only until Apply");
assert.match(calendarSource, /This Week[\s\S]*calendar-weekly-popup__arrow[\s\S]*Next Week/, "weekly activities are vertically ordered");
assert.doesNotMatch(calendarSource, /calendar-day__add/);
const notesSource = readFileSync("src/components/content/MeetingNotesPage.tsx", "utf8");
assert.match(notesSource, /Raw audio stays on this device and browser only/);
assert.match(notesSource, /I have everyone’s consent to record/);
assert.match(notesSource, /external AI is not configured/i);
assert.match(notesSource, /codexConnectionPrimaryLabel\(codexConnection\)/);
assert.match(notesSource, /codex-connection-notice/);
assert.match(notesSource, /개인별 Codex 연결은 현재 지원되지 않습니다/);
assert.match(notesSource, /calendarEventId: event\.id[\s\S]*accountId: event\.accountId/);
assert.match(notesSource, /never exposed through event sharing/);
assert.match(notesSource, /permission-error/);
assert.match(notesSource, /interrupted/);
assert.match(notesSource, /save-error/);
assert.match(notesSource, /Share settings were not fully synchronized/);
assert.match(notesSource, /Retry sharing/);
assert.match(notesSource, /canAccessLocalRecording/);
const calendarCss = readFileSync("src/styles/app.css", "utf8");
assert.match(calendarCss, /\.calendar-page-card\s*\{/);
assert.match(calendarCss, /\.calendar-event__text\s*\{[^}]*text-overflow:\s*ellipsis/);
assert.match(calendarCss, /\.calendar-day-timeline--interactive\s*\{/);
assert.match(calendarCss, /\.calendar-day\.is-selected\s*\{\s*background:/, "selection is a subtle background, not a red border");
assert.match(calendarCss, /\.calendar-day:focus-visible/, "keyboard focus remains independently visible");
const contentSource = readFileSync("src/components/content/index.tsx", "utf8");
assert.match(contentSource, /recordingNamespace=\{profile\.userKey\}/);

console.log("calendar and meeting notes tests passed");
