import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getNavigationRoute, getNavigationRouteFromPath } from "../src/components/navigationRoutes";
import { getFiscalYearForDate, getFiscalYearRange, getMonthCells, getDayKind } from "../src/data/calendarDateUtils";
import { getLocalRecordingKey, getRecordingCapability } from "../src/data/localRecordingStore";
import { canAccessLocalRecording } from "../src/data/meetingNotesApi";

assert.equal(getNavigationRoute("calendar").module, "calendar");
assert.equal(getNavigationRoute("meeting-notes").module, "meetingNotes");
assert.equal(getNavigationRouteFromPath("/calendar").id, "calendar");
assert.equal(getNavigationRouteFromPath("/meeting-notes").id, "meeting-notes");

assert.equal(getFiscalYearForDate("2025-05-31"), "FY25");
assert.equal(getFiscalYearForDate("2025-06-01"), "FY26");
assert.deepEqual(getFiscalYearRange("FY26"), { fromDate: "2025-06-01", toDate: "2026-05-31" });
const june = getMonthCells(2025, 5);
assert.equal(june.length, 42, "month view has a stable six-week grid");
assert.equal(june[0].date, "2025-06-01");
assert.equal(getDayKind("2025-06-01", new Map()), "sunday");
assert.equal(getDayKind("2025-06-07", new Map()), "saturday");
assert.equal(getDayKind("2025-06-06", new Map([["2025-06-06", "Memorial Day"]])), "holiday");

assert.deepEqual(getRecordingCapability({ hasMediaRecorder: false, hasGetUserMedia: true, isSecureContext: true, isMobile: false }),
  { supported: false, reason: "Recording is not supported by this browser." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: true }),
  { supported: false, reason: "Quick recording is unavailable on mobile. Use manual notes instead." });
assert.deepEqual(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: false, isMobile: false }),
  { supported: false, reason: "Recording requires a secure browser context (HTTPS)." });
assert.equal(getRecordingCapability({ hasMediaRecorder: true, hasGetUserMedia: true, isSecureContext: true, isMobile: false }).supported, true);
assert.equal(getLocalRecordingKey(" user/a ", "51"), '["user/a","51"]', "local audio keys are scoped to the authenticated user");
assert.notEqual(getLocalRecordingKey("user/a", "51"), getLocalRecordingKey("user/b", "51"));
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/a"), true, "owners can access their local audio");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: true }, "user/b"), true, "explicit audio grants allow shared-note audio access");
assert.equal(canAccessLocalRecording({ ownerUserKey: "user/a", audioAccess: false }, "user/b"), false, "note text access does not imply audio access");

const navSource = readFileSync("src/data/kpiMockData.ts", "utf8");
assert.match(navSource, /id: "my-activities"[\s\S]*children: activityNavItems/);
assert.match(navSource, /id: "calendar", label: "Calendar"/);
assert.match(navSource, /id: "meeting-notes", label: "Meeting Notes"/);
const calendarSource = readFileSync("src/components/content/CalendarPage.tsx", "utf8");
const calendarStyles = readFileSync("src/styles/app.css", "utf8");
assert.match(calendarStyles, /\.calendar-timeline-event\.is-editable\s*\{[\s\S]*?touch-action:\s*none;/, "editable existing-event touch gestures opt out of native scrolling without trapping read-only events");
assert.match(calendarSource, /holidays\.get/);
assert.match(calendarSource, /PRIVATE[\s\S]*DETAILS/);
assert.doesNotMatch(calendarSource, /BUSY_ONLY/, "Calendar sharing no longer offers a busy-only scope");
assert.match(calendarSource, /const finishBusy = initialCalendarLoadRef\.current \? beginAppBusy\(\) : \(\) => undefined/, "only initial Calendar loading owns the global busy scope");
assert.match(calendarSource, /setCalendarLoading\(true\)[\s\S]*Promise\.all\(/, "Calendar refreshes retain local loading state");
assert.match(calendarSource, /\.finally\(\(\) => \{ if \(active\) setCalendarLoading\(false\); finishBusy\(\); initialCalendarLoadRef\.current = false; \}\)/, "Calendar closes local and initial global loading scopes after success or failure");
assert.equal((calendarSource.match(/beginAppBusy\(\)/g) ?? []).length, 1, "Calendar initial loading has no duplicate busy scope");
assert.match(calendarSource, /onDblClick=\{\(\) => \{[\s\S]*openDay/, "desktop double click opens the selected day");
assert.match(calendarSource, /onDblClick=\{handleTimelineDoubleClick\}/, "desktop timeline double click creates a direct block draft");
assert.match(calendarSource, /lastTouchTapRef[\s\S]*setDayOpen\(true\)/, "mobile double tap opens the selected day");
assert.match(calendarSource, /const beginTimelineCreate[\s\S]*setTimeout[\s\S]*LONG_PRESS_CREATE_DELAY_MS/, "empty timeline creation uses the 500ms long-press contract");
assert.match(calendarSource, /longPressMovementCancels[\s\S]*preventDefault/, "movement cancels before activation and active dragging suppresses scrolling");
assert.match(calendarSource, /preventActivatedTouchScroll[\s\S]*creationPreviewRef\.current[\s\S]*touchmove[\s\S]*passive: false/, "activated mobile long-press uses a non-passive touch guard without blocking pre-activation scroll");
assert.match(calendarSource, /calendar-day-undated[\s\S]*calendar-create-row-preview/, "dragging into the shared top lane renders its row preview");
assert.match(calendarSource, /dayOpen && <oj-c-dialog[\s\S]*dialogTitle=\{selectedDate\}[\s\S]*calendar-day-dialog[\s\S]*calendar-day-detail/, "the selected-day timeline is contained by one JET modal dialog");
assert.match(calendarSource, /import "oj-c\/dialog"/);
assert.match(calendarSource, /import "oj-c\/popup"/);
assert.match(calendarSource, /calendar-editor-options-launcher[\s\S]*<oj-c-popup[\s\S]*calendar-options-popover/, "event options use a JET popup");
assert.match(calendarSource, /calendar-color-[\s\S]*<oj-c-popup[\s\S]*calendar-legend__palette/, "legend colors use a JET popup");
assert.match(calendarSource, /calendar-day-timeline--interactive/);
assert.match(calendarSource, /calendar-timeline-editor[\s\S]*renderDraftEditor/, "timed editing is rendered inside its timeline block");
assert.match(calendarSource, /class="calendar-block-editor__title"/, "the blue event block itself owns the direct title input");
const blockEditorStart = calendarSource.indexOf("const renderDraftEditor");
const blockEditorEnd = calendarSource.indexOf("const eventColor", blockEditorStart);
const blockEditorSource = calendarSource.slice(blockEditorStart, blockEditorEnd);
assert.ok(blockEditorStart >= 0 && blockEditorEnd > blockEditorStart, "block editor source is discoverable");
assert.doesNotMatch(blockEditorSource, /class="calendar-event-form"/, "no create or edit path may render the legacy multi-field event form");
assert.doesNotMatch(blockEditorSource, />From</, "the block editor has no separate From field");
assert.doesNotMatch(blockEditorSource, />To</, "the block editor has no separate To field");
assert.match(calendarSource, /calendar-day-blank-row/, "the combined all-day and unspecified lane retains a consecutive-entry row");
assert.doesNotMatch(calendarSource, /<section class="calendar-inline-editor"/, "there is no separate editor below the calendar");
assert.match(calendarSource, /onCompositionStart[\s\S]*onCompositionEnd/, "inline title save is IME-safe");
assert.match(calendarSource, /event\.isComposing/, "Enter is ignored while the browser reports active IME composition");
const titleMentionEffectStart = calendarSource.indexOf("const trigger = draft ? extractTitleSearchTrigger");
const titleMentionEffectEnd = calendarSource.indexOf("\n  useEffect(() => {\n    if (!mentionEditing)", titleMentionEffectStart);
const titleMentionEffect = calendarSource.slice(titleMentionEffectStart, titleMentionEffectEnd);
assert.match(titleMentionEffect, /setTitleSearchOpen\(true\)/, "the mention result area opens immediately");
assert.doesNotMatch(titleMentionEffect, /setTimeout/, "mention search is immediate rather than artificially delayed");
assert.match(titleMentionEffect, /listCalendarRelatedItems\(lookupFiscalYear, trigger\.query\)/, "@ search uses the Calendar directory that preserves account scope and applies FY only to opportunity search");
assert.match(titleMentionEffect, /listSharingUsers\(trigger\.query\)/, "# sharing-user search calls the directory immediately");
assert.match(titleMentionEffect, /requestIsLatest/, "stale mention search responses are discarded");
assert.match(calendarSource, /setTitleSearchError\("검색 결과를 불러오지 못했습니다\. 다시 시도해 주세요\."\)/, "title search failures are visible inside the inline search region");
assert.match(calendarSource, /setMentionSearchError\("검색 결과를 불러오지 못했습니다\. 다시 시도해 주세요\."\)/, "editable mention search failures are visible inside the mention search region");
assert.match(calendarSource, /class="calendar-inline-search__error" role="alert"/, "inline search errors use an accessible local alert rather than the global busy overlay");
assert.match(calendarSource, /mentionEditing\.kind === "related"[\s\S]*setMentionRelatedOptions\(\[\]\)[\s\S]*listCalendarRelatedItems/, "a new @ request hides stale account, workload, and opportunity choices before loading");
assert.match(calendarSource, /setMentionUserOptions\(\[\]\)[\s\S]*listSharingUsers\(mentionQuery\)/, "a new # request hides stale user choices before loading");
assert.match(calendarSource, /relatedItemType: item\.type[\s\S]*relatedItemId: String\(item\.id\)/, "Calendar stores the selected account, workload, or opportunity as an explicit relationship");
assert.match(calendarSource, /setDraft\(\{ \.\.\.draft, \.\.\.applyRelatedSelection\(draft\.title, item\) \}\)/, "selecting an @ result applies the selected related-item keys to the draft");
assert.match(calendarSource, /titleInputRef\.current\?\.focus\(\)[\s\S]*setSelectionRange/, "mention selection restores the title cursor");
assert.match(calendarSource, /event\.key === "ArrowDown"[\s\S]*event\.key === "ArrowUp"[\s\S]*event\.key === "Escape"/, "mention popover supports arrow navigation and escape");
assert.match(calendarSource, /Weekly Activities/);
assert.match(calendarSource, /fetchWeeklyActivities/);
assert.match(calendarSource, /calendar-event__text/);
assert.doesNotMatch(calendarSource, /title=\{text\}/, "event tooltip is not rendered unconditionally");
assert.match(calendarSource, /일정 다시 열기[\s\S]*일정 취소[\s\S]*일정 삭제/);
assert.match(calendarSource, /timeUnknown: true/, "new events start without a designated time");
assert.doesNotMatch(calendarSource, /applyRelatedSelection\("", item\)/, "relation selection never empties or rewrites the pure title");
assert.match(calendarSource, /const eventDisplayTitle = \(event: CalendarEvent\) => event\.title;/, "the first line remains the pure saved title");
assert.doesNotMatch(calendarSource, /titleWithAccountPrefix/, "legacy account prefixes cannot return to event titles");
assert.match(calendarSource, /permission: "VIEW"[\s\S]*visibility: "DETAILS"/, "# selection stores a VIEW / DETAILS event share");
assert.match(calendarSource, /calendar-event-relations[\s\S]*`@\$\{draftAccountName\}`/, "stored account relation renders as a separate @accountName mention");
assert.match(calendarSource, /eventShares\.map[\s\S]*>#\{sharingUsers\.find/, "stored event shares render as separate #displayName mentions");
assert.match(calendarSource, /class="calendar-event-relations"/, "relationship mentions occupy their own event line");
assert.match(calendarSource, /event\.canEdit \? <button[\s\S]*setMentionEditing/, "owners can edit relation mentions directly from view state");
assert.match(calendarSource, /updateCalendarEvent\(event, toInput\(nextDraft, shares\)\)/, "direct mention edits persist relation and exact replacement/removal shares");
assert.match(calendarSource, /내 일정 색상 변경[\s\S]*비공개 색상 변경[\s\S]*취소됨 색상 변경/, "all fixed legend entries expose color buttons");
assert.match(calendarSource, /direction === "OUTGOING"[\s\S]*status === "ACCEPTED"/, "accepted outgoing requests expose the shared owner to the viewing requester");
assert.match(calendarSource, /getCalendarDisplayPreferences[\s\S]*changeCalendarDisplayPreference/, "viewer colors are persisted through authenticated APIs");
assert.match(calendarSource, /CALENDAR_SHARE_COLORS\.map[\s\S]*Custom 색상/, "legend palette exposes Redwood colors and custom input");
assert.match(calendarSource, /dangerouslySetInnerHTML=\{\{ __html: sanitizeWeeklyActivityHtml/, "weekly popup HTML passes through the shared allow-list sanitizer");
assert.match(calendarSource, /beginResize[\s\S]*resizeTimelineRange/, "vertical pointer resizing uses the one-hour-minimum range helper");
const beginResizeSource = calendarSource.slice(calendarSource.indexOf("const beginResize"), calendarSource.indexOf("const beginMove"));
const beginMoveSource = calendarSource.slice(calendarSource.indexOf("const beginMove"), calendarSource.indexOf("const beginExistingEventGesture"));
assert.match(beginResizeSource, /const captureTarget = document\.documentElement;/);
assert.match(calendarSource, /const existingGesturePointerIdRef = useRef<number \| null>\(null\)/, "existing event gestures remember the first active pointer");
assert.match(beginResizeSource, /if \(existingGesturePointerIdRef\.current !== null\) return;/, "resize ignores another pointer while active");
assert.match(beginResizeSource, /if \(existingGesturePointerIdRef\.current === pointerId\) existingGesturePointerIdRef\.current = null;/, "resize cleanup releases the active pointer slot");
assert.match(beginResizeSource, /captureTarget\.setPointerCapture\(pointerId\)/);
assert.match(beginResizeSource, /captureTarget\.releasePointerCapture\(pointerId\)/);
assert.match(beginResizeSource, /pointercancel/);
assert.match(beginResizeSource, /passive: false/, "existing-event resize captures one pointer on the stable timeline and cleans up cancelled gestures");
assert.match(calendarSource, /calendar-resize-handle--start[\s\S]*calendar-resize-handle--end/, "both timeline edges expose resize handles");
assert.match(calendarSource, /titleEditing \|\| !editing \? <input[\s\S]*<EventTitle text=\{draft\.title/, "new events use an input while single selection keeps an existing title in view state until explicit editing");
assert.match(calendarSource, /onDblClick=\{\(click\)[\s\S]*beginTitleEdit\(event\)/, "desktop double-click enters title editing");
assert.match(calendarSource, /lastEventTitleTouchRef[\s\S]*previous\?\.eventId === event\.id[\s\S]*beginTitleEdit\(event\)/, "mobile double-tap survives the event-to-editor remount and enters title editing");
const editorActions = calendarSource.slice(calendarSource.indexOf('id="calendar-editor-options-launcher"'), calendarSource.indexOf('</span>', calendarSource.indexOf('id="calendar-editor-options-launcher"')));
const actionPositions = ['aria-label="설정"', 'aria-label="저장"', 'aria-label="편집 취소"', '"일정 취소"', '>일정 삭제</button>'].map((token) => editorActions.indexOf(token));
assert.ok(actionPositions.every((position) => position >= 0) && actionPositions.every((position, index) => index === 0 || actionPositions[index - 1] < position), "selection and edit action order distinguishes edit cancel from event cancel");
assert.match(calendarSource, /autoDismiss="none"[\s\S]*onojClose=\{closeSettings\}/, "settings owns its close state instead of racing the launcher click");
assert.match(calendarSource, /if \(!editorMenuOpen\) return;[\s\S]*#calendar-editor-options-launcher, \[aria-label='일정 설정'\][\s\S]*closeSettings\(\)[\s\S]*document\.addEventListener\("pointerdown", handleOutsideSettings, true\)/, "settings closes on outside pointer interaction but not on launcher or popup interaction");
assert.match(calendarSource, /비공개[\s\S]*반복[\s\S]*void applySettings\(\)[\s\S]*>적용</, "settings includes privacy, recurrence, and immediate apply");
assert.match(calendarSource, /const \[settingsDraft, setSettingsDraft\][\s\S]*const closeSettings = \(\) => \{ setEditorMenuOpen\(false\); setSettingsDraft\(null\); \}/, "dismissed settings are discarded independently of the main event draft");
assert.match(calendarSource, /if \(!editing\) \{[\s\S]*setDraft\(nextDraft\)[\s\S]*closeSettings\(\)/, "new-event settings commit locally without requiring an existing event version");
assert.match(calendarSource, /\(titleEditing \|\| !editing\) && editable[\s\S]*aria-label="저장"[\s\S]*\(titleEditing \|\| !editing\)[\s\S]*aria-label="편집 취소"/, "new events expose visible Save and Cancel actions");
assert.doesNotMatch(calendarSource, /추가 설명 없음/, "empty-description placeholder is not duplicated above the event editor");
assert.match(calendarSource, /is-all-day[\s\S]*is-time-unknown[\s\S]*calendar-event__kind/, "month events distinguish all-day and unspecified-time while preserving status markers");
assert.match(calendarSource, /beginMove[\s\S]*onPointerDown=\{\(pointer\) => beginExistingEventGesture/, "timeline blocks support direct pointer movement through touch-aware hit testing");
assert.match(beginMoveSource, /const captureTarget = document\.documentElement;/);
assert.match(beginMoveSource, /captureTarget\.setPointerCapture\(pointerId\)/);
assert.match(beginMoveSource, /captureTarget\.releasePointerCapture\(pointerId\)/);
assert.match(beginMoveSource, /pointercancel/);
assert.match(beginMoveSource, /passive: false/, "existing-event movement captures one pointer on the stable timeline and cleans up cancelled gestures");
assert.match(beginMoveSource, /if \(existingGesturePointerIdRef\.current !== null\) return;/, "move ignores another pointer while active");
assert.match(beginMoveSource, /if \(next\.pointerId !== pointerId\) return;/, "move ignores events from another pointer");
assert.match(beginMoveSource, /Math\.max\(MIN_CALENDAR_DURATION_MINUTES, originalEnd - originalStart\)/, "move preserves at least a sixty-minute event duration");
assert.match(beginResizeSource, /originalEnd - MIN_CALENDAR_DURATION_MINUTES/, "start resize enforces the sixty-minute minimum");
assert.match(calendarSource, /const beginDraftGesture[\s\S]*Math\.max\(MIN_CALENDAR_DURATION_MINUTES, originEnd - originStart\)[\s\S]*originEnd - MIN_CALENDAR_DURATION_MINUTES[\s\S]*originStart \+ MIN_CALENDAR_DURATION_MINUTES/, "open editor move and resize enforce the sixty-minute minimum");
const beginDraftGestureSource = calendarSource.slice(calendarSource.indexOf("const beginDraftGesture"), calendarSource.indexOf("const persistTimelineRange"));
assert.match(beginDraftGestureSource, /updateCalendarEvent\(editing, toInput\(latestDraft, eventShares\)\)/, "selected-editor move and resize persist their changed time without requiring title editing");
assert.match(beginDraftGestureSource, /setEditing\(saved\)[\s\S]*setDraft\(draftFromEvent\(saved\)\)/, "selected-editor time persistence refreshes the event version and canonical draft");
assert.match(calendarSource, /const lookupFiscalYear = getFiscalYearForDate\(draft!\.startDate\)/, "title related-item lookup follows the edited event fiscal year");
assert.match(calendarSource, /listCalendarRelatedItems\(getFiscalYearForDate\(date\), mentionQuery\)/, "selected-event relation lookup follows that event fiscal year");
assert.doesNotMatch(calendarSource, /currentTarget\.setPointerCapture/, "the event node removed by openEdit never owns pointer capture");
assert.match(calendarSource, /const beginExistingEventGesture[\s\S]*pointerType !== "touch"[\s\S]*compactResizeRailStart[\s\S]*"start"[\s\S]*"end"/, "compact touch events reserve a side rail for resize while keeping a practical move surface");
assert.match(calendarSource, /is-touch-compact/, "short events expose explicit compact touch geometry");
assert.match(calendarStyles, /\.calendar-timeline-event\.is-touch-compact \.calendar-resize-handle[\s\S]*width:\s*44px/, "compact resize handles stay finger-addressable without consuming the whole event width");
assert.match(calendarSource, /suppressExistingClickUntilRef[\s\S]*performance\.now\(\) \+ 500[\s\S]*click\.preventDefault\(\)/, "touch completion suppresses the synthetic click that would restore stale event times");
assert.match(calendarSource, /persistTimelineRange[\s\S]*updateCalendarEventEntity/, "drag and resize persist directly without opening the editor");
assert.doesNotMatch(beginResizeSource, /openEdit\(event\)/, "resize never opens the editor");
assert.doesNotMatch(beginMoveSource, /openEdit\(event\)/, "drag never opens the editor");
assert.match(calendarSource, /onDblClick=\{[\s\S]*onEdit\?\.\(\)/, "the title component exposes desktop double-click editing");
assert.match(calendarSource, /<EventTitle text=\{draft\.title\} onEdit=\{\(\) => editing && beginTitleEdit\(editing\)\}/, "only explicit title activation enters title editing for a selected event");
assert.match(calendarSource, /calendar-event__full-title[\s\S]*role="tooltip"/, "truncated event titles expose an accessible full-content tooltip");
assert.match(calendarSource, /ownerDisplayName/, "shared calendar source owner is rendered separately from recipients");
assert.match(calendarSource, /vacation[\s\S]*recurrence[\s\S]*workingDays/, "vacation and recurrence fields are available in the direct editor");
assert.match(calendarSource, /반복 종료일[\s\S]*type="date"[\s\S]*<label>근무일 수[\s\S]*type="number"/, "recurring events collect the required end date and every event can collect a numeric working-day duration");
assert.match(calendarSource, /settingsDraft\.recurrence !== "NONE"[\s\S]*반복 종료일[\s\S]*<label>근무일 수/, "working-day duration remains available when recurrence is NONE");
assert.match(calendarSource, /calendar-undated-kind/, "all-day and unspecified events expose differentiated type marks");
assert.match(calendarSource, /setDraftColor[\s\S]*>적용</, "legend color changes remain draft-only until Apply");
assert.match(calendarSource, /calendar-weekly-popup__box[\s\S]*This Week[\s\S]*calendar-weekly-popup__box[\s\S]*Next Week/, "weekly activities use separate boxes");
assert.doesNotMatch(calendarSource, /calendar-day__add/);
const notesSource = readFileSync("src/components/content/MeetingNotesPage.tsx", "utf8");
assert.match(notesSource, /Raw audio stays on this device and browser only/);
assert.match(notesSource, /I have everyone’s consent to record/);
assert.match(notesSource, /external AI is not configured/i);
assert.match(notesSource, /codexConnectionPrimaryLabel\(codexConnection\)/);
assert.match(notesSource, /codex-connection-notice/);
assert.match(notesSource, /개인별 Codex 연결은 현재 지원되지 않습니다/);
assert.match(notesSource, /calendarEventId: event\.id[\s\S]*accountId: event\.accountId/);
assert.match(notesSource, /never exposed through event sharing/);
assert.match(notesSource, /permission-error/);
assert.match(notesSource, /interrupted/);
assert.match(notesSource, /save-error/);
assert.match(notesSource, /Share settings were not fully synchronized/);
assert.match(notesSource, /Retry sharing/);
assert.match(notesSource, /canAccessLocalRecording/);
const calendarCss = readFileSync("src/styles/app.css", "utf8");
assert.match(calendarCss, /\.calendar-page-card\s*\{/);
assert.match(calendarCss, /\.calendar-event__text\s*\{[^}]*text-overflow:\s*ellipsis/);
assert.match(calendarCss, /\.calendar-day-timeline--interactive\s*\{/);
assert.match(calendarCss, /\.calendar-day\.is-selected\s*\{\s*background:/, "selection is a subtle background, not a red border");
assert.match(calendarCss, /\.calendar-day:focus-visible/, "keyboard focus remains independently visible");
const contentSource = readFileSync("src/components/content/index.tsx", "utf8");
assert.match(contentSource, /recordingNamespace=\{profile\.userKey\}/);

console.log("calendar and meeting notes tests passed");
