import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync("src/components/content/ConsumptionPage.tsx", "utf8");
const content = readFileSync("src/components/content/index.tsx", "utf8");
const accountsPage = readFileSync("src/components/content/AccountsWorkloadsPage.tsx", "utf8");
const navigation = readFileSync("src/data/kpiMockData.ts", "utf8");
const styles = readFileSync("src/styles/app.css", "utf8");

assert.match(navigation, /export const navItems[\s\S]*id: "home"[\s\S]*id: "my-customers"[\s\S]*id: "kpis"[\s\S]*id: "consumption"/, "root navigation order is Home, My Customers, KPI Activities, Consumption");
const customerChildren = navigation.match(/export const customerNavItems[\s\S]*?\];/)?.[0] ?? "";
assert.doesNotMatch(customerChildren, /id: "consumption"/, "Consumption is no longer nested under My Customers");
assert.match(content, /!\['profile', 'users', 'consumption'\]\.includes\(activeRoute\.module\)[\s\S]*kpi-fiscal-year-panel/, "the global Fiscal Year selector is hidden on Consumption and identity pages");

assert.match(content, /activeRoute\.module === "consumption"[\s\S]*<ConsumptionPage/, "Consumption route renders the implemented page");
assert.match(page, /import "ojs\/ojchart"/, "Consumption trend uses Oracle JET Chart");
assert.match(page, /<oj-chart[\s\S]*type="line"/, "linked trend is a JET line chart");
assert.match(page, /allMonths\.flatMap[\s\S]*value === undefined \? \[\]/, "missing Plan ACTUAL months are omitted from the trend instead of rendered as zero");
assert.match(page, /id="consumptionSignalInbox"/, "three-month usual-level change inbox is rendered");
assert.match(page, /Consumption Change Alerts/, "Inbox title states the approved change-alert rule");
assert.match(page, /Previous 3 completed months[\s\S]*Median[\s\S]*MAD[\s\S]*× 3/, "Inbox explains median and MAD thresholds");
assert.match(page, /setSelectedSignalId/, "signal selection drives linked context");
assert.doesNotMatch(page, /role="listitem"/, "signal controls preserve native button semantics");
assert.match(page, /candidate\.serverPlanId === signal\.serverPlanId/, "signal selection preserves exact server Plan ID identity");
assert.match(page, /consumptionSignalPresentation[\s\S]*ABOVE USUAL[\s\S]*BELOW USUAL[\s\S]*NEW USAGE/, "signals visibly expose the approved usual-level badges");
assert.match(page, /signal\.latestActual[\s\S]*signal\.baselineMedian[\s\S]*signal\.changeAmount[\s\S]*signal\.changePercent/, "each alert displays latest Actual, median and change values");
assert.match(page, /signal\.previousDirection[\s\S]*Previous month/, "previous-month direction remains separate from usual-level classification");
assert.doesNotMatch(page.match(/id="consumptionSignalInbox"[\s\S]*?signals\.length === 0/)?.[0] ?? "", /<SignalSparkline/, "compact alert rows leave the four-month sparkline to linked Trend context");
assert.match(page, /consumptionSignalAccessibleLabel[\s\S]*signal\.grade[\s\S]*signal\.allowance[\s\S]*signal\.sparkline/, "alert button accessible names include severity, allowance and all sparkline values");
assert.match(page, /<svg[^>]*class="consumption-sparkline"[^>]*aria-hidden="true"/, "the visual sparkline is hidden from accessibility APIs after its values enter the button name");
assert.doesNotMatch(page, /3-Month Plan Trend Alerts|RISING|FALLING|Month-over-Month|month-over-month|\bMoM\b|Latest actual month vs immediately previous month|SPIKE|DROP|Prioritized detection|Change Signal Inbox|New baseline/, "legacy trend and monthly-change language is removed");
assert.doesNotMatch(styles, /is-rising|is-falling|is-rise|is-fall/, "legacy trend CSS is removed");
assert.match(page, /accept="\.csv,text\/csv"/, "runtime CSV import accepts CSV files");
assert.match(page, /parseConsumptionCsv/, "CSV import uses the normalized parser");
assert.match(page, /seedForecastMonths/, "the next quarter receives editable forecast cells");
assert.match(page, /data-forecast-cell/, "forecast cells expose a browser-verifiable edit contract");
assert.match(page, /type EditCell = Readonly<\{ planKey:/, "the active editor is keyed by stable account-scoped Plan identity");
assert.match(page, /plan\.id === planKey/, "Forecast updates change only the selected stable Plan row");
assert.match(page, /savedPlans\.find\(\(plan\) => plan\.id === series\.id\)/, "dirty comparison uses the same stable Plan identity");
assert.match(page, /onDblClick[\s\S]*beginForecastEdit/, "double-click enters Forecast editing");
assert.match(page, /event\.key === "Enter"[\s\S]*commitForecastEdit/, "Enter commits the current cell into the page draft");
assert.match(page, /event\.key === "Escape"[\s\S]*cancelForecastEdit/, "Escape restores the original value and value type");
assert.match(page, /restoreForecastEntry\(plan, saved, editCell\.month\)/, "Escape preserves an editable future Actual as Actual instead of manufacturing a Forecast draft");
assert.match(page, /hasDraftChanges[\s\S]*isSaving \? "Saving…" : "Save"[\s\S]*>Cancel</, "Save and Cancel appear only for draft changes");
assert.match(page, /await saveConsumptionForecasts\(apiEtag, updates\)[\s\S]*adoptWorkspace/, "Save adopts the authoritative backend snapshot");
assert.match(page, /setDraftPlans\(clonePlans\(savedPlans\)\)/, "Cancel restores the whole saved snapshot");
assert.match(page, /onNavigationGuardChange/, "Consumption Draft reuses the KAP navigation guard contract");
assert.match(page, /window\.confirm\(/, "Leaving with a Draft requires an explicit decision");
assert.match(page, /data-readonly=\{expandable \? "account" : undefined\}/, "only Multiple account aggregate rows are marked read-only");
assert.match(page, /data-readonly=\{!editable && actual \? "actual"/, "past Actual cells are read-only while backend-declared future periods remain editable");
assert.match(page, /Quarter Total[\s\S]*PreQ Gap/, "each quarter column group ends with Total and PreQ Gap");
assert.match(styles, /\.consumption-table-scroll\s*\{[^}]*overflow-x:\s*auto[^}]*scrollbar-width:\s*none/, "the month and quarter area scrolls with its native scrollbar hidden");
assert.match(page, /id="consumptionTableContent" class="consumption-table-content"/, "horizontal movement controls are scoped by the table content container");
assert.match(styles, /\.consumption-table-content\s*\{[^}]*position:\s*relative/, "the table content owns the controls' positioning context");
assert.match(styles, /\.consumption-scroll-controls\s*\{[^}]*position:\s*absolute/, "table movement controls remain inside the table instead of following the viewport");
assert.doesNotMatch(styles, /\.consumption-scroll-controls\s*\{[^}]*position:\s*fixed/, "desktop table movement controls must not escape into Trend or other sections");
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.consumption-summary-cards\s*\{[^}]*grid-template-columns:\s*repeat\(5, minmax\(9rem, 1fr\)\)[^}]*overflow-x:\s*auto/, "mobile summary cards remain readable in a contained horizontal rail");
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.consumption-scroll-controls\s*\{[^}]*position:\s*absolute[^}]*transform:\s*none/, "mobile table controls stay inside the table panel instead of obscuring the viewport");
assert.match(page, /consumption-scroll-controls[\s\S]*Move table left[\s\S]*Move table right/, "fixed left and right table movement controls are rendered");
assert.match(page, /event\.key === "ArrowLeft"[\s\S]*moveTableHorizontally\(-1\)[\s\S]*event\.key === "ArrowRight"[\s\S]*moveTableHorizontally\(1\)/, "focused table supports ArrowLeft and ArrowRight movement");
const accountColumnRule = styles.match(/\.consumption-account-column\s*\{([^}]*)\}/)?.[1] ?? "";
assert.match(accountColumnRule, /position:\s*sticky/, "Account column uses sticky positioning");
assert.match(accountColumnRule, /left:\s*0/, "Account column stays fixed at the left edge");
assert.doesNotMatch(page, /Sold To/, "Sold To never appears in the UI model");
assert.match(page, /fetchConsumptionWorkspace/, "Consumption loads the authoritative backend workspace");
assert.match(page, /previewConsumptionImport/, "CSV import calls server-side preview validation");
assert.match(page, /applyConsumptionImport/, "CSV import uses atomic server-side apply");
assert.doesNotMatch(page, /window\.confirm\(`Preview passed:/, "CSV import does not use a browser confirm dialog");
assert.match(page, /<oj-dialog[\s\S]*Consumption CSV import/, "CSV import confirmation uses an Oracle JET dialog");
assert.match(page, /<oj-progress-circle[\s\S]*Importing Consumption CSV/, "CSV import exposes an in-progress state");
assert.match(page, /Successful rows[\s\S]*Failed rows[\s\S]*Loaded plans/, "CSV import completion reports success, failure and loaded counts");
assert.match(page, /saveConsumptionForecasts/, "Forecast Save uses the atomic backend API");
assert.match(page, /ConsumptionConflictError/, "HTTP 409 is handled as a typed conflict");
assert.match(page, /Saved baseline[\s\S]*My draft[\s\S]*Current server/, "409 UX compares saved, draft and current server values");
assert.match(page, /useState<ConsumptionPlan\[\]>\(\[\]\)/, "production starts without rendering synthetic Consumption data");
assert.match(page, /dataMode === "fallback"[\s\S]*Saved in local fallback[\s\S]*dataMode !== "backend"/, "local-only fallback is explicit and production fails closed before Save");
assert.match(page, /canUseConsumptionFallback\(error\)[\s\S]*setSavedPlans\(fallbackPlans\)/, "synthetic plans are adopted only after a localhost fallback decision");
assert.match(page, /setApiEtag\(""\)[\s\S]*setDataMode\("fallback"\)/, "local import fallback clears the prior server ETag");
assert.match(page, /if \(isSaving\) return;[\s\S]*setIsSaving\(true\)[\s\S]*finally[\s\S]*setIsSaving\(false\)/, "Forecast Save submissions are serialized by an in-flight guard");
assert.match(page, /disabled=\{dataMode === "loading" \|\| isSaving \|\| importPhase === "previewing"/, "Import stays disabled during load, save and in-flight import");
assert.match(page, /if \(!file \|\| dataMode === "loading" \|\| isSaving \|\| importPhase === "previewing"/, "Import handler rejects loading, save and duplicate import races");
assert.match(page, /if \(isSaving \|\| \(dataMode !== "backend" && dataMode !== "fallback"\)\) return;/, "Forecast editing locks while save is in flight");
assert.match(page, /aria-label=\{`\$\{series\.endUser\} \$\{month\} forecast`\}[\s\S]*disabled=\{isSaving\}/, "an already open forecast editor is disabled while saving");
assert.match(page, /id="consumptionFromQuarter"[\s\S]*id="consumptionToQuarter"[\s\S]*isConsumptionQuarterRangeValid[\s\S]*Apply/, "From/To Quarter controls validate reversed ranges before Apply");
assert.match(page, /fetchConsumptionWorkspace\(\{ fromQuarter, toQuarter \}\)/, "Apply reloads the API with the selected quarter range");
assert.match(page, /workspace\.fromQuarter[\s\S]*workspace\.toQuarter[\s\S]*workspace\.editablePeriodIds[\s\S]*workspace\.displayQuarterOrder/, "backend range metadata is adopted as authoritative UI state");
assert.match(page, /useState\("__all__"\)/, "trend defaults to All accounts");
assert.match(page, /All accounts · Total/, "the default trend is the total across all accounts");
assert.doesNotMatch(page, /Search accounts/, "the separate Trend Search field is removed");
assert.match(page, /role="combobox"[\s\S]*aria-label="Search or select trend plan"[\s\S]*role="listbox"[\s\S]*filteredPlans\.map/, "one searchable selection component includes every matching Plan");
assert.match(page, /event\.key === "ArrowDown"[\s\S]*event\.key === "ArrowUp"[\s\S]*event\.key === "Enter"[\s\S]*event\.key === "Escape"[\s\S]*aria-activedescendant/, "the Plan combobox supports active-option keyboard selection and dismissal");
assert.match(page, /getConsumptionPlanLabel\(plan\)/, "selector labels are Account - Workload (Plan ID), falling back to Account (Plan ID)");
assert.match(page, /selectedSeriesId[\s\S]*draftPlans\.find\(\(plan\) => plan\.id === selectedSeriesId\)/, "same-account Plans retain independent trend selection by stable Plan identity");
assert.match(page, /selectSignal[\s\S]*signal\.customer[\s\S]*signal\.planId[\s\S]*setSelectedSeriesId\(plan\.id\)/, "signal selection links the exact Plan ID into trend context");
assert.match(page, /const signals = useMemo\(\(\) => serverSignals \?\? \[\]/, "Inbox renders only meaningful anomalies returned by the backend");
assert.doesNotMatch(page, /serverSignals \?\? detectConsumptionSignals/, "the Inbox never invents client-side anomalies");
assert.match(page, /const trendPoints[\s\S]*selectedPlan\.actuals\[month\][\s\S]*value === undefined \? \[\]/, "Trend renders ACTUAL values only and omits Forecast values");
assert.doesNotMatch(page.match(/const trendPoints[\s\S]*?const trendDataProvider/)?.[0] ?? "", /selectedPlan\.forecasts/, "Trend never falls back to Forecast values");
assert.match(page, /id="consumptionAccountSelector"[\s\S]*onClick=\{\(\) => \{ setAccountSelectorOpen\(true\)/, "every Plan selector click opens the list immediately, including an already-focused input");
assert.match(page, /editablePeriodIds\.has\(month\)/, "only backend-declared period IDs are editable");
assert.match(page, /buildDisplayQuarterSummaries/, "table totals and PreQ gaps are calculated independently of backend display ordering");
assert.match(page, /displayQuarterOrder\.flatMap/, "table columns follow the backend display quarter order");
assert.match(page, /const expandable = account\.plans\.length > 1/, "only Multiple End Users are expandable");
assert.match(page, /expandable \? \([\s\S]*consumption-account-toggle[\s\S]*\) : \(/, "single-plan End Users render without an expand control");
assert.match(page, /renderQuarterCells\(singlePlan, false\)/, "single-plan account rows render editable detailed Forecast cells");
assert.match(page, /renderQuarterCells\(account, true\)/, "Multiple aggregate rows are always read-only");
assert.match(page, /filterActiveConsumptionPlans\(draftPlans, currentFiscalMonth\)[\s\S]*aggregateConsumptionAccounts\(visiblePlans\)/, "the End User / Plan table excludes only plans with zero previous/current ACTUAL");
assert.match(page, /class="consumption-leading"[\s\S]*class="consumption-disclosure-slot"/, "Account and End User leading content shares one aligned grid");
assert.match(page, /class="consumption-account-toggle"[\s\S]*aria-expanded=\{expanded\}[\s\S]*aria-label=/, "Multiple rows expose a named native-button disclosure with aria-expanded");
assert.match(styles, /\.consumption-account-toggle:hover[\s\S]*\.consumption-account-toggle:focus-visible/, "Multiple disclosure has visible hover and keyboard focus states");
assert.match(styles, /\.consumption-forecast-cell\s*\{[^}]*background:[^}]*box-shadow:\s*none/, "editable Forecast cells use background color without an underline");
assert.match(page, /const status = editablePeriodIds\.has\(month\) \? "FORECAST" : "ACTUAL"[\s\S]*consumption-month-status/, "month headings visibly distinguish Actual and Forecast from backend editability metadata");
assert.match(page, /singlePlan\?\.customer[\s\S]*singlePlan\?\.workload[\s\S]*singlePlan\?\.endUser[\s\S]*singlePlan\?\.planId[\s\S]*singlePlan\?\.dataCenter/, "single Plan rows show Account, mapped Workload, End User, Plan ID and DC from API fields");
assert.match(page, /plan\.customer[\s\S]*plan\.workload[\s\S]*plan\.endUser[\s\S]*plan\.planId[\s\S]*plan\.dataCenter/, "expanded Plan rows show Account, mapped Workload, End User, Plan ID and DC from API fields");
assert.match(page, /rangeInitialized && rangeTouched && !rangeValid/, "reversed range validation waits for initialized, meaningful user interaction");
assert.match(page, /const editable = editablePeriodIds\.has\(month\)[\s\S]*series\.forecasts\[month\] \?\? series\.actuals\[month\] \?\? null[\s\S]*if \(!readOnly && editable/, "backend-declared future months remain editable regardless of whether their loaded value is typed ACTUAL or FORECAST");
assert.match(page, /const savedValue = savedPlan\?\.forecasts\[month\] \?\? savedPlan\?\.actuals\[month\][\s\S]*const dirty = savedValue !== value/, "an editable future ACTUAL is not marked draft until its displayed value changes");
assert.match(page, /onFocus=\{\(event\) => \(event\.currentTarget as HTMLInputElement\)\.select\(\)\}/, "opening a Forecast editor immediately selects its complete value");
assert.doesNotMatch(page, /display only/i, "Account / End User rows no longer show display-only copy");
assert.match(page, /function ConsumptionTruncatedText[\s\S]*scrollWidth > element\.clientWidth/, "full-text help is enabled only when the Account and Workload text is actually clipped");
assert.match(page, /createPortal[\s\S]*consumption-clipped-tooltip/, "clipped Account and Workload help is portaled outside overflow-clipped table containers");
assert.match(page, /ConsumptionTruncatedText text=\{`\$\{singlePlan\?\.customer[\s\S]*singlePlan\?\.workload/, "the fast tooltip targets the Account (Workload) text rather than the entire row");
assert.match(styles, /\.consumption-quarter-heading\.is-forecast[\s\S]*\.consumption-month-heading\.is-forecast[\s\S]*\.consumption-quarter-total\.is-forecast[\s\S]*\.consumption-preq-gap\.is-forecast/, "Forecast quarter, month, value total and PreQ Gap areas have a distinct background treatment");
assert.match(styles, /\.consumption-table-title\s*\{[^}]*font-size:\s*clamp\(/, "End User / Plan table title is enlarged responsively");
assert.match(styles, /\.consumption-section-heading h2\s*\{[^}]*font-size:\s*clamp\(1\.35rem, 2vw, 1\.75rem\)/, "Alerts and Trend titles match the End User / Plan title scale");
assert.match(page, /consumption-signal-grade is-\$\{signal\.grade\.toLowerCase\(\)\}/, "CRITICAL and HIGH severities use semantic badge classes");
assert.match(styles, /\.consumption-signal-grade\.is-critical\s*\{[^}]*background:[^}]*color:/, "critical severity has an accessible high-emphasis badge");
assert.match(styles, /\.consumption-signal-grade\.is-high\s*\{[^}]*background:[^}]*color:/, "high severity has an accessible warning badge");
assert.match(styles, /\.consumption-table thead \.consumption-account-column\s*\{[^}]*font-size:[^}]*padding-left:[^}]*text-align:\s*left/, "Account / End User header is enlarged and aligned with the leading text");
assert.match(styles, /@media \(max-width: 720px\)[\s\S]*\.consumption-signal\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\)/, "small-screen Change Alerts collapse into one non-overlapping content column");
assert.doesNotMatch(page, /Detect unusual monthly change, inspect its Plan context, and manage the next-quarter Forecast\./, "the requested Consumption helper copy is removed");
assert.match(page, /const linkedPlan = draftPlans\.find[\s\S]*Workload:[\s\S]*linkedPlan\?\.workload/, "Change Alert list shows the linked Workload");
assert.doesNotMatch(page.match(/id="consumptionSignalInbox"[\s\S]*?signals\.length === 0/)?.[0] ?? "", /SignalSparkline|consumption-signal-change|consumption-signal-direction/, "Change Alert rows omit detailed change, direction and sparkline data that belongs in Trend");
assert.match(page, /consumption-pulse-toggle[\s\S]*aria-expanded=\{pulseExpanded\}[\s\S]*Consumption Change Alerts & Trend/, "Alerts and Trend share one disclosure control");
assert.match(page, /consumption-table-toggle[\s\S]*aria-expanded=\{tableExpanded\}/, "End User Plan table has an independent disclosure control");
assert.match(page, /visibleTableRowCount > 10 \? "consumption-table-scroll is-scrollable-y"/, "vertical table scrolling starts only after more than ten visible rows");
assert.match(styles, /\.consumption-table-scroll\.is-scrollable-y\s*\{[^}]*max-height:\s*calc\(6\.5rem \+ 10 \* 3\.25rem[^}]*scrollbar-width:\s*thin/, "table viewport is sized for ten data rows and exposes a vertical scrollbar only when needed");
assert.match(styles, /\.consumption-table-scroll\.is-scrollable-y::-webkit-scrollbar\s*\{[^}]*display:\s*block/, "WebKit browsers show the over-ten-row vertical scrollbar");
assert.match(styles, /\.consumption-table thead tr:first-child th\s*\{[^}]*position:\s*sticky[^}]*top:\s*0/, "first table header row stays fixed during vertical scroll");
assert.match(styles, /\.consumption-table thead tr:nth-child\(2\) th\s*\{[^}]*position:\s*sticky[^}]*top:\s*3\.25rem/, "second table header row stays fixed below the first");
assert.doesNotMatch(page, /Backend connected/, "Consumption omits Backend connected status copy");
assert.match(page, /consumption-metric-help[\s\S]*data-tooltip="Median is the middle[\s\S]*data-tooltip="MAD/, "Median and MAD expose concise hover and focus explanations");
assert.match(styles, /\.consumption-clipped-tooltip\s*\{[^}]*max-width:\s*min\(28rem, calc\(100vw - 1rem\)\)[^}]*position:\s*fixed[^}]*z-index:/, "portaled full-text help is constrained to the viewport and remains above cards");
assert.match(page, /text=\{account\.customer\} focusable=\{false\}/, "account disclosure button must not contain a nested focusable tooltip trigger");
assert.match(accountsPage, /rows\.length === 0 \? "accounts-workloads-page is-empty" : "accounts-workloads-page"/, "empty Accounts & Workloads data opts into compact Fiscal Year spacing");
assert.match(styles, /\.kpi-content:has\(\.accounts-workloads-page\)\s*\{[^}]*gap:\s*1rem/, "populated Accounts & Workloads uses the standard Portfolio and Weekly Activities gap");
assert.match(styles, /\.kpi-content:has\(\.accounts-workloads-page\.is-empty\)\s*\{[^}]*gap:\s*0\.25rem/, "an empty Accounts & Workloads page stays close to Fiscal Year without dead space");
assert.match(content, /!\['profile', 'users', 'consumption'\]\.includes\(activeRoute\.module\)/, "global Fiscal Year is hidden on Consumption");
assert.doesNotMatch(page, /Double-click a Forecast cell\. Enter keeps the page draft; Esc restores the edit-entry value\./, "the requested Forecast editing helper copy is removed");

console.log("consumptionUiContract tests passed");
