import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync("src/components/content/ConsumptionPage.tsx", "utf8");
const content = readFileSync("src/components/content/index.tsx", "utf8");
const navigation = readFileSync("src/data/kpiMockData.ts", "utf8");
const styles = readFileSync("src/styles/app.css", "utf8");

assert.match(navigation, /export const navItems[\s\S]*id: "home"[\s\S]*id: "my-customers"[\s\S]*id: "kpis"[\s\S]*id: "consumption"/, "root navigation order is Home, My Customers, KPI Activities, Consumption");
const customerChildren = navigation.match(/export const customerNavItems[\s\S]*?\];/)?.[0] ?? "";
assert.doesNotMatch(customerChildren, /id: "consumption"/, "Consumption is no longer nested under My Customers");
assert.match(content, /!\['profile', 'users'\]\.includes\(activeRoute\.module\)[\s\S]*kpi-fiscal-year-panel/, "the global Fiscal Year selector remains visible on Consumption and is hidden only on identity pages");

assert.match(content, /activeRoute\.module === "consumption"[\s\S]*<ConsumptionPage/, "Consumption route renders the implemented page");
assert.match(page, /import "ojs\/ojchart"/, "Consumption trend uses Oracle JET Chart");
assert.match(page, /<oj-chart[\s\S]*type="line"/, "linked trend is a JET line chart");
assert.match(page, /allMonths\.flatMap[\s\S]*value === null \? \[\]/, "missing Plan months are omitted from the trend instead of rendered as zero");
assert.match(page, /id="consumptionSignalInbox"/, "Change Signal Inbox is rendered");
assert.match(page, /setSelectedSignalId/, "signal selection drives linked context");
assert.match(page, /consumptionSignalDirection[\s\S]*signal\.changeAmount >= 0[\s\S]*Rise[\s\S]*Fall/, "signals visibly expose rise and fall direction");
assert.match(page, /accept="\.csv,text\/csv"/, "runtime CSV import accepts CSV files");
assert.match(page, /parseConsumptionCsv/, "CSV import uses the normalized parser");
assert.match(page, /seedForecastMonths/, "the next quarter receives editable forecast cells");
assert.match(page, /data-forecast-cell/, "forecast cells expose a browser-verifiable edit contract");
assert.match(page, /type EditCell = Readonly<\{ planKey:/, "the active editor is keyed by stable account-scoped Plan identity");
assert.match(page, /plan\.id === planKey/, "Forecast updates change only the selected stable Plan row");
assert.match(page, /savedPlans\.find\(\(plan\) => plan\.id === series\.id\)/, "dirty comparison uses the same stable Plan identity");
assert.match(page, /onDblClick[\s\S]*beginForecastEdit/, "double-click enters Forecast editing");
assert.match(page, /event\.key === "Enter"[\s\S]*commitForecastEdit/, "Enter commits the current cell into the page draft");
assert.match(page, /event\.key === "Escape"[\s\S]*cancelForecastEdit/, "Escape restores the current edit-entry value");
assert.match(page, /hasDraftChanges[\s\S]*isSaving \? "Saving…" : "Save"[\s\S]*>Cancel</, "Save and Cancel appear only for draft changes");
assert.match(page, /await saveConsumptionForecasts\(apiEtag, updates\)[\s\S]*adoptWorkspace/, "Save adopts the authoritative backend snapshot");
assert.match(page, /setDraftPlans\(clonePlans\(savedPlans\)\)/, "Cancel restores the whole saved snapshot");
assert.match(page, /onNavigationGuardChange/, "Consumption Draft reuses the KAP navigation guard contract");
assert.match(page, /window\.confirm\(/, "Leaving with a Draft requires an explicit decision");
assert.match(page, /data-readonly=\{expandable \? "account" : undefined\}/, "only Multiple account aggregate rows are marked read-only");
assert.match(page, /data-readonly=\{actual \? "actual"/, "Actual cells are read-only");
assert.match(page, /Quarter Total[\s\S]*PreQ Gap/, "each quarter column group ends with Total and PreQ Gap");
assert.match(styles, /\.consumption-table-scroll\s*\{[^}]*overflow-x:\s*auto[^}]*scrollbar-width:\s*none/, "the month and quarter area scrolls with its native scrollbar hidden");
assert.match(styles, /\.consumption-scroll-controls\s*\{[^}]*position:\s*fixed/, "table movement controls stay available at the viewport edge like Accounts & Workloads");
assert.match(page, /consumption-scroll-controls[\s\S]*Move table left[\s\S]*Move table right/, "fixed left and right table movement controls are rendered");
assert.match(page, /event\.key === "ArrowLeft"[\s\S]*moveTableHorizontally\(-1\)[\s\S]*event\.key === "ArrowRight"[\s\S]*moveTableHorizontally\(1\)/, "focused table supports ArrowLeft and ArrowRight movement");
const accountColumnRule = styles.match(/\.consumption-account-column\s*\{([^}]*)\}/)?.[1] ?? "";
assert.match(accountColumnRule, /position:\s*sticky/, "Account column uses sticky positioning");
assert.match(accountColumnRule, /left:\s*0/, "Account column stays fixed at the left edge");
assert.doesNotMatch(page, /Sold To/, "Sold To never appears in the UI model");
assert.match(page, /fetchConsumptionWorkspace/, "Consumption loads the authoritative backend workspace");
assert.match(page, /previewConsumptionImport/, "CSV import calls server-side preview validation");
assert.match(page, /applyConsumptionImport/, "CSV import uses atomic server-side apply");
assert.doesNotMatch(page, /window\.confirm\(`Preview passed:/, "CSV import does not use a browser confirm dialog");
assert.match(page, /<oj-dialog[\s\S]*Consumption CSV import/, "CSV import confirmation uses an Oracle JET dialog");
assert.match(page, /<oj-progress-circle[\s\S]*Importing Consumption CSV/, "CSV import exposes an in-progress state");
assert.match(page, /Successful rows[\s\S]*Failed rows[\s\S]*Loaded plans/, "CSV import completion reports success, failure and loaded counts");
assert.match(page, /saveConsumptionForecasts/, "Forecast Save uses the atomic backend API");
assert.match(page, /ConsumptionConflictError/, "HTTP 409 is handled as a typed conflict");
assert.match(page, /Saved baseline[\s\S]*My draft[\s\S]*Current server/, "409 UX compares saved, draft and current server values");
assert.match(page, /useState<ConsumptionPlan\[\]>\(\[\]\)/, "production starts without rendering synthetic Consumption data");
assert.match(page, /dataMode === "fallback"[\s\S]*Saved in local fallback[\s\S]*dataMode !== "backend"/, "local-only fallback is explicit and production fails closed before Save");
assert.match(page, /canUseConsumptionFallback\(error\)[\s\S]*setSavedPlans\(fallbackPlans\)/, "synthetic plans are adopted only after a localhost fallback decision");
assert.match(page, /setApiEtag\(""\)[\s\S]*setDataMode\("fallback"\)/, "local import fallback clears the prior server ETag");
assert.match(page, /if \(isSaving\) return;[\s\S]*setIsSaving\(true\)[\s\S]*finally[\s\S]*setIsSaving\(false\)/, "Forecast Save submissions are serialized by an in-flight guard");
assert.match(page, /disabled=\{dataMode === "loading" \|\| isSaving \|\| importPhase === "previewing"/, "Import stays disabled during load, save and in-flight import");
assert.match(page, /if \(!file \|\| dataMode === "loading" \|\| isSaving \|\| importPhase === "previewing"/, "Import handler rejects loading, save and duplicate import races");
assert.match(page, /if \(isSaving \|\| \(dataMode !== "backend" && dataMode !== "fallback"\)\) return;/, "Forecast editing locks while save is in flight");
assert.match(page, /aria-label=\{`\$\{series\.endUser\} \$\{month\} forecast`\}[\s\S]*disabled=\{isSaving\}/, "an already open forecast editor is disabled while saving");
assert.match(page, /id="consumptionFromQuarter"[\s\S]*id="consumptionToQuarter"[\s\S]*isConsumptionQuarterRangeValid[\s\S]*Apply/, "From/To Quarter controls validate reversed ranges before Apply");
assert.match(page, /fetchConsumptionWorkspace\(\{ fromQuarter, toQuarter \}\)/, "Apply reloads the API with the selected quarter range");
assert.match(page, /workspace\.fromQuarter[\s\S]*workspace\.toQuarter[\s\S]*workspace\.editablePeriodIds[\s\S]*workspace\.displayQuarterOrder/, "backend range metadata is adopted as authoritative UI state");
assert.match(page, /useState\("__all__"\)/, "trend defaults to All accounts");
assert.match(page, /All accounts · Total/, "the default trend is the total across all accounts");
assert.doesNotMatch(page, /Search accounts/, "the separate Trend Search field is removed");
assert.match(page, /role="combobox"[\s\S]*aria-label="Search or select trend account"[\s\S]*role="listbox"[\s\S]*filteredAccounts\.map/, "one searchable selection component includes every matching account");
assert.match(page, /selectSignal[\s\S]*setSelectedAccount/, "signal selection links the account into trend context");
assert.match(page, /editablePeriodIds\.has\(month\)/, "only backend-declared period IDs are editable");
assert.match(page, /buildDisplayQuarterSummaries/, "table totals and PreQ gaps are calculated independently of backend display ordering");
assert.match(page, /displayQuarterOrder\.flatMap/, "table columns follow the backend display quarter order");
assert.match(page, /const expandable = account\.plans\.length > 1/, "only Multiple End Users are expandable");
assert.match(page, /expandable \? \([\s\S]*consumption-account-toggle[\s\S]*\) : \(/, "single-plan End Users render without an expand control");
assert.match(page, /renderQuarterCells\(singlePlan, false\)/, "single-plan account rows render editable detailed Forecast cells");
assert.match(page, /renderQuarterCells\(account, true\)/, "Multiple aggregate rows are always read-only");
assert.match(styles, /\.consumption-forecast-cell\s*\{[^}]*background:[^}]*box-shadow:\s*none/, "editable Forecast cells use background color without an underline");
assert.match(page, /const status = editablePeriodIds\.has\(month\) \? "FORECAST" : "ACTUAL"[\s\S]*consumption-month-status/, "month headings visibly distinguish Actual and Forecast from backend editability metadata");
assert.match(page, /singlePlan\?\.customer[\s\S]*singlePlan\?\.workload[\s\S]*singlePlan\?\.endUser[\s\S]*singlePlan\?\.planId[\s\S]*singlePlan\?\.dataCenter/, "single Plan rows show Account, mapped Workload, End User, Plan ID and DC from API fields");
assert.match(page, /plan\.customer[\s\S]*plan\.workload[\s\S]*plan\.endUser[\s\S]*plan\.planId[\s\S]*plan\.dataCenter/, "expanded Plan rows show Account, mapped Workload, End User, Plan ID and DC from API fields");
assert.match(page, /rangeInitialized && rangeTouched && !rangeValid/, "reversed range validation waits for initialized, meaningful user interaction");
assert.doesNotMatch(page, /Detect unusual monthly change, inspect its Plan context, and manage the next-quarter Forecast\./, "the requested Consumption helper copy is removed");
assert.doesNotMatch(page, /Double-click a Forecast cell\. Enter keeps the page draft; Esc restores the edit-entry value\./, "the requested Forecast editing helper copy is removed");

console.log("consumptionUiContract tests passed");
