import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const page = fs.readFileSync(path.resolve("src/components/content/KpiSpreadsheetPage.tsx"), "utf8");
const api = fs.readFileSync(path.resolve("src/data/kpiSpreadsheetApi.ts"), "utf8");
const contract = fs.readFileSync(path.resolve("src/data/kpiSpreadsheet.ts"), "utf8");
const main = fs.readFileSync(path.resolve("src/main.js"), "utf8");
const content = fs.readFileSync(path.resolve("src/components/content/index.tsx"), "utf8");
const app = fs.readFileSync(path.resolve("src/components/app.tsx"), "utf8");

assert.match(main, /waitSeconds:\s*(?:[3-9]\d|\d{3,})/, "KPI's expanded JET dependency graph must tolerate Tailnet load latency");
assert.match(page, /import "ojs\/ojtable"/, "KPI tables must use Oracle JET Data Table");
assert.match(page, /import "ojs\/ojdatetimepicker"/, "date cells must load Oracle JET Date Picker");
assert.match(page, /<oj-table/, "detail tables must render an oj-table");
assert.doesNotMatch(page, />Edit</, "Edit button must be removed");
assert.match(page, /onDblClick/, "double-click must enter cell edit mode");
assert.match(page, /requestAnimationFrame/, "cell editor focus must wait for JET table rendering");
assert.match(page, /\.focus\(\)/, "the opened cell editor must receive input focus");
assert.match(page, /event\.key === "Enter"/, "Enter must commit the active editor to the draft");
assert.match(page, /const stopTableInteraction = \(event: Event\) => event\.stopPropagation\(\)/, "KPI editors must isolate input events from oj-table navigation");
assert.match(page, /onKeyDown=\{stopTableInteraction\}/, "editor Enter must not bubble to the Select column");
assert.match(page, /onDblClick=\{stopTableInteraction\}/, "double-clicking an active editor must keep focus in that editor");
assert.match(page, /onMouseDown=\{stopTableInteraction\}/, "selector and editor pointer actions must not activate oj-table focus navigation");
assert.match(page, /is-unsaved-cell/, "changed cells must be visually marked");
assert.match(page, /is-unsaved-row/, "changed rows must be visually marked");
assert.match(page, /kpi-manage-time-reflected-row/, "Manage Time Reflected must mark the full row");
assert.match(page, /<oj-input-date/, "Delivery Date must use oj-input-date");
assert.match(page, /<textarea/, "SR Description must use a textarea editor");
assert.match(page, /kpi-quarter-status-label--achieved/, "quarter status must use a green label class");
assert.match(page, /kpi-quarter-status-label--not-achieved/, "quarter status must use a red label class");
assert.match(page, /kpi-quarter-status-label--in-progress/, "quarter status must use a yellow label class");
assert.match(page, /kpi-quarter-status-label--not-started/, "quarter status must use a gray label class");
assert.match(page, /kpi-quarter-count-label/, "quarter Count must use the same status color label");
assert.match(page, /import "ojs\/ojdialog"/, "navigation and delete confirmations must use Oracle JET Dialog");
assert.match(page, /import "ojs\/ojbutton"/, "KPI dialog actions must use Oracle JET buttons");
assert.match(page, /<oj-popup/, "truncated SR Description must expose its full value in an Oracle JET Popup");
assert.match(page, /kpi-workload-results-popup/, "workload search results must render in a popup layer outside oj-table clipping");
assert.match(page, /const \[activated, setActivated\] = useState\(false\)/, "workload options must wait for an explicit editor click");
assert.match(page, /onClick=\{\(\) => \{ setActivated\(true\)/, "workload search must activate only after the editor is explicitly clicked");
assert.match(page, /event\.key === "Enter"[\s\S]*onCommit\(\)/, "Enter without choosing a workload must preserve the current value");
assert.doesNotMatch(page, /event\.key === "Enter" && options\[0\]/, "Enter must never auto-select the first workload result");
assert.match(page, />선택 안함</, "workload results must offer restoration of the original value");
assert.match(page, /collision:\s*"flipfit"/, "workload popup must fit or flip at the viewport edge");
assert.match(page, /return \(\) => \{ if \(popup\?\.isOpen\(\)\) popup\.close\(\); \}/,
  "an unmounted workload editor must close its relocated Oracle JET popup layer");
assert.match(page, /Save and Continue/);
assert.match(page, /Discard and Continue/);
assert.match(page, />Stay</);
assert.match(page, /Delete selected KPI activities/);
assert.match(page, /selectedQuarter/);
assert.doesNotMatch(page, />Refresh</, "the redundant KPI Refresh button must be removed");
assert.match(page, /setSelectedQuarter\(\(current\) => current === quarter \? null : quarter\)/, "clicking the selected Quarter again must clear the filter");
assert.match(page, /const selectQuarter[\s\S]*setSelectedIds\(new Set\(\)\)/, "every quarter transition must clear row selection");
assert.match(page, /const selectedRows = visibleRows\.filter/, "delete candidates must be scoped to currently visible rows");
assert.match(page, /const closeDescriptionPopup[\s\S]*cancelDescriptionPopupOpen\(\)[\s\S]*descriptionPopupRef\.current\?\.close\(\)/, "mouseleave and blur must cancel a pending popup open");
assert.match(page, /onMouseLeave=\{closeDescriptionPopup\}[\s\S]*onBlur=\{closeDescriptionPopup\}/);
assert.match(page, /drafts\.filter[\s\S]*authoritativeRows/, "new draft rows must be placed before saved rows");
assert.match(contract, /Account \/ Workload \/ Oppty\.No/);
assert.match(page, /Solution Design/);
assert.match(page, /Solution Proposal/);
assert.match(page, /Solution Deployment/);
assert.match(page, /role="progressbar"/, "D1 summary must expose accessible progress bars");
assert.match(page, /Sales Stage ACR[\s\S]*USD K/);

const toolbarStart = page.indexOf('<div class="kpi-activity-toolbar"');
const toolbarEnd = page.indexOf("<Summary rows=", toolbarStart);
const toolbar = page.slice(toolbarStart, toolbarEnd);
assert.ok(toolbarStart >= 0 && toolbarEnd > toolbarStart);
assert.match(toolbar, /kpi-activity-toolbar__left/);
assert.match(toolbar, /kpi-activity-toolbar__right/);
assert.ok(toolbar.indexOf(">Save<") < toolbar.indexOf(">Cancel<"));
assert.match(toolbar, /toolbarActions\.includes\("save"\).*Save/s);
assert.match(toolbar, /toolbarActions\.includes\("cancel"\).*Cancel/s);
assert.match(toolbar, /toolbarActions\.includes\("delete"\).*Delete/s);
assert.match(page, /Promise\.allSettled\(draftSnapshot\.map/s, "Save must send every changed row snapshot");
assert.match(page, /Promise\.allSettled\(rowsToDelete\.map/s, "Delete must support multiple selected rows");
assert.match(page, /sessionVersion\.current !== saveSession/, "late Save responses must not update a different FY\/route session");
assert.match(page, /setReloadVersion\(\(current\) => current \+ 1\)/, "discarded mutation responses must trigger a fresh active-route fetch");
assert.doesNotMatch(page, /deferredDraftsRef/, "navigation guard must replace deferred stale toolbar state");
assert.match(page, /requestVersion\.current !== requestVersionAtStart/, "workload pagination must reject stale query responses");
assert.match(page, /const \[editorValue, setEditorValue\] = useState\(value\)/, "text editors must buffer keystrokes locally instead of rebuilding the table per character");
assert.doesNotMatch(page, /ensureDraft\(row\)/, "opening an unchanged editor must not create a dirty draft");
assert.match(page, /setDrafts\(\[\]\)/, "Cancel\/save success must clear drafts");
assert.match(api, /workloadId/, "save payload must preserve stable workloadId");
assert.doesNotMatch(page, /<th>Rows<\/th>/);
assert.match(page, /overview\?\.target/);
assert.match(page, /listKpiOverview/);
assert.match(page, /onNavigationGuardChange\(drafts\.length > 0 \? requestProtectedNavigation : null\)/, "the KPI page must register its JET-dialog guard only while drafts exist");
assert.match(content, /onKpiNavigationGuardChange[\s\S]*onNavigationGuardChange=\{onKpiNavigationGuardChange\}/, "Content must forward the KPI guard registration to App");
assert.match(app, /onKpiNavigationGuardChange=\{handleKpiNavigationGuardChange\}/);
assert.match(app, /window\.addEventListener\("beforeunload", handleBeforeUnload\)/, "KPI drafts must participate in browser unload protection");
assert.match(app, /if \(kpiGuard\) kpiGuard\(route\.pageTitle, navigate\)/, "App side navigation must use the registered JET dialog guard");
assert.match(app, /if \(kpiGuard\) kpiGuard\(nextFiscalYear, changeFiscalYear\)/, "App fiscal-year changes must use the registered JET dialog guard");
assert.match(app, /pendingKpiPopstatePromptRef\.current = \{[\s\S]*confirmedKpiPopstateRetryRef\.current = \{ historyIndex: destinationIndex, href: destinationHref \}[\s\S]*window\.history\.go\(-restorationDelta\)[\s\S]*window\.history\.go\(restorationDelta\)/, "rejected popstate must register one confirmed retry and restore the current history entry before prompting");
assert.match(app, /if \(confirmedRetry\) confirmedKpiPopstateRetryRef\.current = null/, "the popstate retry bypass must be consumed exactly once");
assert.match(app, /UNSAVED_WEEKLY_ACTIVITY_MESSAGE[\s\S]*window\.confirm/, "the existing Weekly Activity native guard must remain intact");
assert.doesNotMatch(page, /window\.confirm/, "the KPI guard must keep the centrally mounted Oracle JET dialog");
assert.match(page, /<oj-button[\s\S]*Save and Continue/, "navigation actions must use JET Button components");
assert.match(page, /<oj-button[\s\S]*Delete/, "delete confirmation actions must use JET Button components");
assert.match(page, /selectionMode=\{\{ row: "none", column: "none" \}\}/, "ordinary row and cell clicks must not control selection");
assert.match(page, /<Selector/, "only an explicit Oracle JET selector checkbox may change selected rows");

console.log("kpiActivityUiContract tests passed");
