import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const page = fs.readFileSync(path.resolve("src/components/content/KpiSpreadsheetPage.tsx"), "utf8");
const api = fs.readFileSync(path.resolve("src/data/kpiSpreadsheetApi.ts"), "utf8");
const contract = fs.readFileSync(path.resolve("src/data/kpiSpreadsheet.ts"), "utf8");
const main = fs.readFileSync(path.resolve("src/main.js"), "utf8");

assert.match(main, /waitSeconds:\s*(?:[3-9]\d|\d{3,})/, "KPI's expanded JET dependency graph must tolerate Tailnet load latency");
assert.match(page, /import "ojs\/ojtable"/, "KPI tables must use Oracle JET Data Table");
assert.match(page, /import "ojs\/ojdatetimepicker"/, "date cells must load Oracle JET Date Picker");
assert.match(page, /<oj-table/, "detail tables must render an oj-table");
assert.doesNotMatch(page, />Edit</, "Edit button must be removed");
assert.match(page, /onDblClick/, "double-click must enter cell edit mode");
assert.match(page, /event\.key === "Enter"/, "Enter must commit the active editor to the draft");
assert.match(page, /is-unsaved-cell/, "changed cells must be visually marked");
assert.match(page, /is-unsaved-row/, "changed rows must be visually marked");
assert.match(page, /kpi-manage-time-reflected-row/, "Manage Time Reflected must mark the full row");
assert.match(page, /<oj-input-date/, "Delivery Date must use oj-input-date");
assert.match(contract, /Account \/ Workload \/ Oppty\.No/);
assert.match(page, /Solution Design/);
assert.match(page, /Solution Proposal/);
assert.match(page, /Solution Deployment/);
assert.match(page, /role="progressbar"/, "D1 summary must expose accessible progress bars");
assert.match(page, /Sales Stage ACR USD K/);

const toolbarStart = page.indexOf('<div class="kpi-activity-toolbar"');
const toolbarEnd = page.indexOf("<Summary rows=", toolbarStart);
const toolbar = page.slice(toolbarStart, toolbarEnd);
assert.ok(toolbarStart >= 0 && toolbarEnd > toolbarStart);
assert.match(toolbar, /kpi-activity-toolbar__left/);
assert.match(toolbar, /kpi-activity-toolbar__right/);
assert.ok(toolbar.indexOf(">Save<") < toolbar.indexOf(">Cancel<"));
assert.match(toolbar, /toolbarActions\.includes\("save"\).*Save/s);
assert.match(toolbar, /toolbarActions\.includes\("cancel"\).*Cancel/s);
assert.match(toolbar, /toolbarActions\.includes\("delete"\).*Delete/s);
assert.match(page, /Promise\.allSettled\(draftSnapshot\.map/s, "Save must send every changed row snapshot");
assert.match(page, /Promise\.allSettled\(rowsToDelete\.map/s, "Delete must support multiple selected rows");
assert.match(page, /sessionVersion\.current !== saveSession/, "late Save responses must not update a different FY\/route session");
assert.match(page, /setReloadVersion\(\(current\) => current \+ 1\)/, "discarded mutation responses must trigger a fresh active-route fetch");
assert.match(page, /deferredDraftsRef\.current\.set\(saveSessionKey, failedDrafts\)/, "failed stale-session saves must retain their drafts for retry");
assert.match(page, /deferredDraftsRef\.current\.set\(previousSessionKey, currentDraftsRef\.current\)/, "later route switches must retain existing failed retry drafts");
assert.match(page, /requestVersion\.current !== requestVersionAtStart/, "workload pagination must reject stale query responses");
assert.match(page, /setDrafts\(\[\]\)/, "Cancel\/save success must clear drafts");
assert.match(api, /workloadId/, "save payload must preserve stable workloadId");
assert.doesNotMatch(page, /<th>Rows<\/th>/);
assert.match(page, /overview\?\.target/);
assert.match(page, /listKpiOverview/);

console.log("kpiActivityUiContract tests passed");
