import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getNavigationRouteFromPath } from "../src/components/navigationRoutes";

const page = readFileSync("src/components/content/WeeklyActivitiesPage.tsx", "utf8");
const editor = readFileSync("src/components/content/SharedWeeklyActivityEditor.tsx", "utf8");
const css = readFileSync("src/styles/app.css", "utf8");
const content = readFileSync("src/components/content/index.tsx", "utf8");
const app = readFileSync("src/components/app.tsx", "utf8");
const requirements = readFileSync("요구사항.md", "utf8");
const design = readFileSync("디자인.md", "utf8");
const tasks = readFileSync("태스크.md", "utf8");

assert.equal(getNavigationRouteFromPath("/weekly-activities").module, "weeklyActivities");
assert.match(page, /Adaptive|weekly-activity-card__sections/);
assert.match(page, /fetchWeeklyActivities/);
assert.match(page, /createWeeklyActivity/);
assert.match(page, /updateWeeklyActivity/);
assert.match(page, /From Date/);
assert.match(page, /To Date/);
assert.match(page, /Content/);
assert.match(page, /oj-input-date/);
assert.match(page, /Save Row/);
assert.match(page, /Cancel/);
assert.match(page, /This Week · Completed/);
assert.match(page, /Next Week · Planned/);
assert.doesNotMatch(page, /ellipsis|overflow menu/i);
assert.equal((page.match(/dangerouslySetInnerHTML/g) ?? []).length, 1, "one activity HTML sink");
assert.match(page, /dangerouslySetInnerHTML=\{\{ __html: sanitizeWeeklyActivityHtml\(html\) \}\}/);
assert.equal((editor.match(/dangerouslySetInnerHTML/g) ?? []).length, 1, "one preview HTML sink");
assert.match(editor, /dangerouslySetInnerHTML=\{\{ __html: sanitizeWeeklyActivityHtml\(inactiveHtml\) \}\}/);
assert.doesNotMatch(readFileSync("src/components/content/weeklyActivityEditorSession.ts", "utf8"), /element\.tagName === "SPAN"/, "safe color and size styles are retained on every allowed tag, not only span");
assert.match(page, /const requestId = requestGuardRef\.current\.begin\(\)/, "each list request gets a generation");
assert.match(page, /if \(!requestGuardRef\.current\.isLatest\(requestId\)\) return;/, "stale list responses are ignored");
assert.match(page, /if \(clearBeforeLoad\) \{\s*setItems\(\[\]\);\s*setTotalElements\(0\);/, "new searches clear stale results before loading");
assert.match(page, /reconcileWeeklyActivityMutation\(current, saved, query\)/, "the mutation response is reconciled against the active query before refresh");
assert.match(page, /fetchWeeklyActivityLoadedWindow\(query\)[\s\S]*setItems\(authoritative\.items\)/, "post-save authoritative refresh preserves every loaded page");
assert.doesNotMatch(page, /await load\(\{ \.\.\.query, page: 0 \}, false, false\)/, "post-save refresh does not collapse the loaded window back to page zero");
assert.match(page, /const controlsBusy = loading \|\| loadingMore \|\| saving;/, "all conflicting controls share one busy state");
assert.match(page, /window\.addEventListener\("beforeunload", handleBeforeUnload\)/, "reload warns while an editor is open");
assert.match(page, /onDirtyStateChange\?\.\(Boolean\(editSession\)\)/, "the page reports unsaved add and edit sessions");
assert.match(content, /<WeeklyActivitiesPage onDirtyStateChange=\{onWeeklyActivitiesDraftStateChange\} \/>/);
assert.match(app, /confirmWeeklyActivitiesNavigation[\s\S]*weeklyActivitiesDraftActiveRef\.current[\s\S]*window\.confirm\(UNSAVED_WEEKLY_ACTIVITY_MESSAGE\)/, "navigation confirmation is centralized around the active weekly draft ref");
assert.match(app, /handlePopState[\s\S]*confirmWeeklyActivitiesNavigation\(route, window\.location\.href\)/, "browser Back and Forward pass the full destination URL, including hash, to the dirty guard");
assert.match(app, /window\.history\.replaceState\(withHistoryIndex\(window\.history\.state, currentHistoryIndex\)/, "the current browser entry is indexed without replacing the stack");
assert.match(app, /getRejectedPopstateDelta\(historyIndexRef\.current, event\.state\)[\s\S]*window\.history\.go\(restorationDelta\)/, "rejected Back and Forward restore the indexed current entry with a signed delta");
assert.doesNotMatch(app, /restoreOnReject[\s\S]*history\.pushState/, "popstate rejection never duplicates or destroys entries with pushState");
assert.match(app, /shouldReleaseWeeklyActivityDraft\(previousRoute\.id, route\.id\)[\s\S]*weeklyActivitiesDraftActiveRef\.current = false/, "approval releases ownership only when navigation unmounts WeeklyActivitiesPage");
assert.match(app, /handleNavigate[\s\S]*confirmWeeklyActivitiesNavigation\(route, destinationHref\)/, "side navigation confirms before discarding a weekly draft");
assert.match(app, /handleItemClick[\s\S]*event\.preventDefault\(\)[\s\S]*event\.stopPropagation\(\)[\s\S]*onNavigate\(item\)/, "handled leaf navigation suppresses JET's later native-hash rewrite after the indexed app route push");
assert.match(app, /handleItemClick[\s\S]*event\.button !== 0[\s\S]*event\.ctrlKey[\s\S]*return;/, "modifier and non-primary side-navigation clicks keep their native non-current-context behavior");
assert.match(app, /document\.addEventListener\("click", handleDocumentNavigationClick, true\)/, "capture-phase anchor guard protects unsaved weekly drafts before JET link defaults");
assert.match(app, /handleDocumentNavigationClick[\s\S]*anchor\.closest\("oj-navigation-list"\)[\s\S]*anchor\.dataset\.appNavigation === "true"[\s\S]*event\.preventDefault\(\)[\s\S]*return;/, "the global hash guard preserves JET side-navigation routing while suppressing only a handled leaf anchor's native hash default");
assert.match(app, /handleDocumentNavigationClick[\s\S]*event\.preventDefault\(\)[\s\S]*event\.stopImmediatePropagation\(\)/, "rejected anchor navigation is fully cancelled");
assert.match(app, /href: anchor\.href/, "anchor navigation uses the browser-resolved full href and therefore respects document base URL semantics");
assert.match(app, /isSameDocumentNavigation\(window\.location\.href, destinationHref\)[\s\S]*history\.pushState\(withHistoryIndex/, "approved hash navigation creates an indexed entry so rejected Back and Forward can restore without stack mutation");
assert.doesNotMatch(app, /handleDocumentNavigationClick[\s\S]{0,180}if \(!weeklyActivitiesDraftActiveRef\.current/, "same-document entries are indexed even before a draft opens");
for (const document of [requirements, design, tasks]) {
  assert.match(document, /UTF-8/);
  assert.match(document, /BOM/);
  assert.match(document, /mojibake|문자 깨짐/);
}
assert.match(css, /\.weekly-activity-active-editor:focus-within/, "the active editor surface exposes a visible focus state");
assert.doesNotMatch(css, /var\(--kpi-surface-soft\)|var\(--kpi-text\)/, "weekly activity styles use only declared KPI tokens");

assert.equal((editor.match(/class="weekly-activity-toolbar"/g) ?? []).length, 1, "one shared toolbar composition");
assert.equal((editor.match(/class="weekly-activity-target-selector"/g) ?? []).length, 1, "one target selector");
assert.equal((editor.match(/new QuillRuntime\(/g) ?? []).length, 1, "one Quill constructor site");
assert.match(editor, /thisWeek: "This Week · Completed"/);
assert.match(editor, /nextWeek: "Next Week · Planned"/);
assert.match(editor, /Editing: \{TARGET_LABELS\[activeTarget\]\}/);
assert.match(editor, /\{TARGET_LABELS\[inactiveTarget\]\} \(read only\)/);
assert.match(editor, /ql-list" value="bullet"/);
assert.match(editor, /ql-list" value="ordered"/);
assert.match(editor, /ql-undo/);
assert.match(editor, /ql-redo/);
assert.match(editor, /handlers:\s*\{/);
assert.match(editor, /quill\.history\.clear\(\)/);
assert.doesNotMatch(editor, /indent|align/);

assert.match(css, /\.weekly-activity-card__sections,[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\)/);
assert.match(css, /\.weekly-activity-active-editor \.ql-container \{[^}]*height: auto;/);
assert.match(css, /@media \(max-width: 640px\)[\s\S]*\.weekly-activity-card__sections,[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);

console.log("weeklyActivitiesUiContract tests passed");
